### ISSUE TITLE
Add support for configuring volumes to the preseed file

### ISSUE THREAD

**Issue by amartin3225** [canonical/lxd#10956]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4
   * LXC version: 5.0.1
   * LXD version: 5.0.1
   * Storage backend in use: any

# Issue description

I am interested in configuring LXD using a preseed file. One of the things I want to set is `storage.images_volume` as outlined [here](https://discuss.linuxcontainers.org/t/why-lxd-store-some-squashfs-images-outside-the-main-storage/7678/2) to a custom location. I can define the storage pool within the preseed file, but I cannot define a storage volume. It seems that the volume must exist for `storage.images_volume` to be set (e.g. it isn’t created automatically), so I'd like to request that the ability to configure volumes be added to the preseed file.

# Steps to reproduce

 1. Create a preseed file with `storage.images_volume` set
 2. Attempt to load the preseed file with `cat /tmp/preseed.yml | lxd init --preseed`
 3. See the error:

```
Error: Failed to update server configuration: Unable to load storage volume "default/images": Storage pool volume not found
```

# Information to attach

Here is an example preseed file that can reproduce this issue:

```
config:
  storage.images_volume: default/images
storage_pools:
- config:
    size: 10GB
  name: default
  driver: dir
profiles:
- name: example
  devices:
    images:
      path: /tmp/images
      pool: default
      source: images
      type: disk
```
