### ISSUE TITLE
LXD Network Forward firewall rule generation is inefficient.

### ISSUE THREAD

**Issue by v3ss0n** [canonical/lxd#11911]
i tried dumping firewall rules and i found 3.4MB of rules.

On closer inspection , it is because   UDP port forward rule for a WebRTC video conf app we developing.
```
ports:
- description: ""
  protocol: udp
  listen_port: 443,3000-60000
  target_port: ""
  target_address: 10.xx.xxx.xx
```
it have over 50000 lines of
```
-A POSTROUTING -s 10.xx.xx.xx/32 -d 10.xx.xx.xx/32 -p udp -m udp --dport 4000 -m comment --comment "generated for LXD network-forward lxdbr1" -j MASQUERADE
.....
-A POSTROUTING -s 10.xx.xx.xx/32 -d 10.xx.xx.xx/32 -p udp -m udp --dport 60000 -m comment --comment "generated for LXD network-forward lxdbr1" -j MASQUERADE
```
Isn't it better to use  `--match multiport --dports 4000:60000` ?
