### ISSUE TITLE
LXD 5.16 - Creating new virtual machine instances import again the image on creation

### ISSUE THREAD

**Issue by f-bn** [canonical/lxd#12067]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0-76-generic
   * LXC version: 5.0.2
   * LXD version: 5.16
   * Storage backend in use: ZFS

# Issue description

Hello,

When playing today with the newest version of LXD, I encountered an issue when launching new virtual machines. Each time I create a new instances, LXD is unpacking the image inside the storage pool. There we can see that some images with the same prefix id are moved into the `deleted/images` dataset.

Before launching anything, everything is good : 

```console
$ zfs list
NAME                           USED  AVAIL     REFER  MOUNTPOINT
lxd                           1.96M   922G       24K  legacy
lxd/buckets                     24K   922G       24K  legacy
lxd/containers                  24K   922G       24K  legacy
lxd/custom                      24K   922G       24K  legacy
lxd/deleted                    144K   922G       24K  legacy
lxd/deleted/buckets             24K   922G       24K  legacy
lxd/deleted/containers          24K   922G       24K  legacy
lxd/deleted/custom              24K   922G       24K  legacy
lxd/deleted/images              24K   922G       24K  legacy
lxd/deleted/virtual-machines    24K   922G       24K  legacy
lxd/images                      24K   922G       24K  legacy
lxd/virtual-machines            24K   922G       24K  legacy
```
Then, I imported a custom image of mine and then launch a VM, looks good : 

```console
$ lxc image list
+-----------------+--------------+--------+--------------------------------------+--------------+-----------------+-----------+------------------------------+
|      ALIAS      | FINGERPRINT  | PUBLIC |             DESCRIPTION              | ARCHITECTURE |      TYPE       |   SIZE    |         UPLOAD DATE          |
+-----------------+--------------+--------+--------------------------------------+--------------+-----------------+-----------+------------------------------+
| ubuntu/22.04-vm | 2f2b933a79ab | no     | Ubuntu jammy (default-20230722_1738) | x86_64       | VIRTUAL-MACHINE | 267.30MiB | Jul 22, 2023 at 5:41pm (UTC) |
+-----------------+--------------+--------+--------------------------------------+--------------+-----------------+-----------+------------------------------+

# My profile specify only the network and storage pool to use, but also disable Secure Boot
$ lxc launch ubuntu/22.04-vm v1 -p vm
Creating v1
Retrieving image: Unpack: 100% (1.05GB/s)

$ lxc list
+------+---------+--------------------+------+-----------------+-----------+
| NAME |  STATE  |        IPV4        | IPV6 |      TYPE       | SNAPSHOTS |
+------+---------+--------------------+------+-----------------+-----------+
| v1   | RUNNING | 10.0.2.24 (enp5s0) |      | VIRTUAL-MACHINE | 0         |
+------+---------+--------------------+------+-----------------+-----------+

$ zfs list
NAME                                                                                USED  AVAIL     REFER  MOUNTPOINT
lxd                                                                                 388M   922G       24K  legacy
lxd/buckets                                                                          24K   922G       24K  legacy
lxd/containers                                                                       24K   922G       24K  legacy
lxd/custom                                                                           24K   922G       24K  legacy
lxd/deleted                                                                         144K   922G       24K  legacy
lxd/deleted/buckets                                                                  24K   922G       24K  legacy
lxd/deleted/containers                                                               24K   922G       24K  legacy
lxd/deleted/custom                                                                   24K   922G       24K  legacy
lxd/deleted/images                                                                   24K   922G       24K  legacy
lxd/deleted/virtual-machines                                                         24K   922G       24K  legacy
lxd/images                                                                          376M   922G       24K  legacy
lxd/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47          29K   100M       29K  legacy
lxd/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47.block   376M   922G      376M  -
lxd/virtual-machines                                                               9.81M   922G       24K  legacy
lxd/virtual-machines/k8s_v1                                                        7.67M  92.3M     7.67M  legacy
lxd/virtual-machines/k8s_v1.block                                                  2.12M   922G      377M  -
```
Then launching a second and third VM, LXD is unpacking again and again the image and then move the image with the same prefix into the `deleted/images` dataset : 

```console
$ lxc launch ubuntu/22.04-vm v2 -p vm
Creating v2
Retrieving image: Unpack: 100% (1.03GB/s)
$ lxc launch ubuntu/22.04-vm v3 -p vm
Creating v3
Retrieving image: Unpack: 100% (940.89MB/s)

$ zfs list
NAME                                                                                                                             USED  AVAIL     REFER  MOUNTPOINT
lxd                                                                                                                             1.13G   921G       24K  legacy
lxd/buckets                                                                                                                       24K   921G       24K  legacy
lxd/containers                                                                                                                    24K   921G       24K  legacy
lxd/custom                                                                                                                        24K   921G       24K  legacy
lxd/deleted                                                                                                                      752M   921G       24K  legacy
lxd/deleted/buckets                                                                                                               24K   921G       24K  legacy
lxd/deleted/containers                                                                                                            24K   921G       24K  legacy
lxd/deleted/custom                                                                                                                24K   921G       24K  legacy
lxd/deleted/images                                                                                                               751M   921G       24K  legacy
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_276dc1a9-4b94-4549-a9bf-d8b3dad9d485          29K   100M       29K  legacy
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_276dc1a9-4b94-4549-a9bf-d8b3dad9d485.block   376M   921G      376M  -
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_844334be-c373-4aa7-8770-93e687ad29c2          29K   100M       29K  legacy
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_844334be-c373-4aa7-8770-93e687ad29c2.block   376M   921G      376M  -
lxd/deleted/virtual-machines                                                                                                      24K   921G       24K  legacy
lxd/images                                                                                                                       376M   921G       24K  legacy
lxd/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47                                                       29K   100M       29K  legacy
lxd/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47.block                                                376M   921G      376M  -
lxd/virtual-machines                                                                                                            29.1M   921G       24K  legacy
lxd/virtual-machines/k8s_v1                                                                                                     7.67M  92.3M     7.67M  legacy
lxd/virtual-machines/k8s_v1.block                                                                                               2.12M   921G      377M  -
lxd/virtual-machines/k8s_v2                                                                                                     7.67M  92.3M     7.67M  legacy
lxd/virtual-machines/k8s_v2.block                                                                                               2.13M   921G      377M  -
lxd/virtual-machines/k8s_v3                                                                                                     7.67M  92.3M     7.67M  legacy
lxd/virtual-machines/k8s_v3.block                                                                                               1.85M   921G      377M  -
```
I also use the following `restricted.*` keys in my current project, but I'm not sure if it's related to this issue (no problem in 5.15) : 

```console
$ lxc project show k8s
config:
  features.images: "false"
  features.networks: "false"
  features.profiles: "true"
  features.storage.buckets: "true"
  features.storage.volumes: "true"
  restricted: "true"
  restricted.backups: allow
  restricted.containers.interception: allow
  restricted.containers.privilege: unprivileged
  restricted.devices.disk: managed
  restricted.devices.nic: managed
  restricted.networks.access: lxd-k8s
  restricted.snapshots: allow
 ```
I tried in another project, same problem, but with containers everything is fine, there is no unpacking nor deleted images for them :

```console
$ lxc launch ubuntu/22.04-vm v1 --project sandbox
Creating v1
Retrieving image: Unpack: 100% (952.97MB/s)
$ lxc launch ubuntu/22.04-vm v2 --project sandbox
Creating v2
Retrieving image: Unpack: 100% (540.72MB/s)

$ lxc launch ubuntu/22.04 c1 --project sandbox
Creating c1
Retrieving image: Unpack: 100% (147.75MB/s)
$ lxc launch ubuntu/22.04 c2 --project sandbox
Creating c2
Starting c2 <=== no unpacking
$ lxc launch ubuntu/22.04 c3 --project sandbox
Creating c3
Starting c3 <=== no unpacking

$ zfs list
NAME                                                                                                                             USED  AVAIL     REFER  MOUNTPOINT
lxd                                                                                                                             2.13G   920G       24K  legacy
lxd/buckets                                                                                                                       24K   920G       24K  legacy
lxd/containers                                                                                                                  4.45M   920G       24K  legacy
lxd/containers/sandbox_c1                                                                                                       1.48M   920G      253M  -
lxd/containers/sandbox_c2                                                                                                       1.47M   920G      253M  -
lxd/containers/sandbox_c3                                                                                                       1.48M   920G      253M  -
lxd/custom                                                                                                                        24K   920G       24K  legacy
lxd/deleted                                                                                                                     1.47G   920G       24K  legacy
lxd/deleted/buckets                                                                                                               24K   920G       24K  legacy
lxd/deleted/containers                                                                                                            24K   920G       24K  legacy
lxd/deleted/custom                                                                                                                24K   920G       24K  legacy
lxd/deleted/images                                                                                                              1.47G   920G       24K  legacy
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_276dc1a9-4b94-4549-a9bf-d8b3dad9d485          29K   100M       29K  legacy
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_276dc1a9-4b94-4549-a9bf-d8b3dad9d485.block   376M   920G      376M  -
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_296e5255-c3d6-4dd7-9cbe-8a86efd52028          29K   100M       29K  legacy
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_296e5255-c3d6-4dd7-9cbe-8a86efd52028.block   376M   920G      376M  -
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_5e1332a7-7eec-4480-89a2-fc165ec9acc7          29K   100M       29K  legacy
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_5e1332a7-7eec-4480-89a2-fc165ec9acc7.block   376M   920G      376M  -
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_844334be-c373-4aa7-8770-93e687ad29c2          29K   100M       29K  legacy
lxd/deleted/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47_844334be-c373-4aa7-8770-93e687ad29c2.block   376M   920G      376M  -
lxd/deleted/virtual-machines                                                                                                      24K   920G       24K  legacy
lxd/images                                                                                                                       628M   920G       24K  legacy
lxd/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47                                                       29K   100M       29K  legacy
lxd/images/2f2b933a79ab9364b0be4cb55768bd1eb097cefc5409e3d5148ca0d7a8e9bf47.block                                                376M   920G      376M  -
lxd/images/39dbb7b67c00b58337661553857fe218190f03f154fa5c377affdce8d8f540a3_ext4                                                 252M   920G      252M  -
lxd/virtual-machines                                                                                                            46.6M   920G       24K  legacy
lxd/virtual-machines/k8s_v1                                                                                                     7.67M  92.3M     7.67M  legacy
lxd/virtual-machines/k8s_v1.block                                                                                               2.12M   920G      377M  -
lxd/virtual-machines/k8s_v2                                                                                                     7.67M  92.3M     7.67M  legacy
lxd/virtual-machines/k8s_v2.block                                                                                               2.13M   920G      377M  -
lxd/virtual-machines/k8s_v3                                                                                                     7.67M  92.3M     7.67M  legacy
lxd/virtual-machines/k8s_v3.block                                                                                               2.12M   920G      377M  -
lxd/virtual-machines/sandbox_v1                                                                                                 7.67M  92.3M     7.68M  legacy
lxd/virtual-machines/sandbox_v1.block                                                                                           1.81M   920G      377M  -
lxd/virtual-machines/sandbox_v2                                                                                                 7.67M  92.3M     7.68M  legacy
lxd/virtual-machines/sandbox_v2.block                                                                                              1K   920G      376M  -
```

I don't encounter this problem with LXD 5.15, there is no issue of unpacking at each VM creation : 

```console
$ lxc version
Client version: 5.15
Server version: 5.15

$ lxc launch ubuntu/22.04-vm v1 -p vm
Creating v1
Retrieving image: Unpack: 100% (530.12MB/s)

$ lxc launch ubuntu/22.04-vm v2 -p vm
Creating v2
Starting v2 <=== no unpacking

$ zfs list
NAME                                                                                     USED  AVAIL     REFER  MOUNTPOINT
lxd                                                                                      397M   922G       24K  legacy
lxd/buckets                                                                               24K   922G       24K  legacy
lxd/containers                                                                            24K   922G       24K  legacy
lxd/custom                                                                                24K   922G       24K  legacy
lxd/deleted                                                                              144K   922G       24K  legacy
lxd/deleted/buckets                                                                       24K   922G       24K  legacy
lxd/deleted/containers                                                                    24K   922G       24K  legacy
lxd/deleted/custom                                                                        24K   922G       24K  legacy
lxd/deleted/images                                                                        24K   922G       24K  legacy
lxd/deleted/virtual-machines                                                              24K   922G       24K  legacy
lxd/images                                                                               376M   922G       24K  legacy
lxd/images/6f900ad07e1669395187db8eece94e3011de0cafdfc2a2cb7dc8b639bcff1916               29K   100M       29K  legacy
lxd/images/6f900ad07e1669395187db8eece94e3011de0cafdfc2a2cb7dc8b639bcff1916_ext4.block   376M   922G      376M  -
lxd/virtual-machines                                                                    18.5M   922G       24K  legacy
lxd/virtual-machines/k8s_v1                                                             7.68M  92.3M     7.68M  legacy
lxd/virtual-machines/k8s_v1.block                                                       2.22M   922G      377M  -
lxd/virtual-machines/k8s_v2                                                             7.68M  92.3M     7.68M  legacy
lxd/virtual-machines/k8s_v2.block                                                        921K   922G      376M  -
```

Thanks !

PS: I can also provide additional tests if needed :)

# Steps to reproduce

Done above

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [ ] Container log (`lxc info NAME --show-log`)
 - [ ] Container configuration (`lxc config show NAME --expanded`)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

**Comment by tomponline** [comment]
Please can you take this one @monstermunchkin

**Comment by monstermunchkin** [comment]
@f-bn I'm unable to reproduce this issue. Could you please provide the LXD debug log in order for us to see what's going?

**Comment by f-bn** [comment]
Hello @monstermunchkin 

I did some additional tests and didn't had the issue when having already existing VM images in 5.15 and then refresh the LXD snap. However, when completely removing my images in ZFS pool after version upgrade, re-importing them and trying to boot new images, the problem happens.

Here is the debug log as requested (I created 2 VM with debug mode, `v1` and `v3`) :  [lxd.log](https://github.com/canonical/lxd/files/12144817/lxd.log)

**Comment by monstermunchkin** [comment]
@f-bn What's your zfs pool config? (`lxc storage show <pool>`)

**Comment by f-bn** [comment]
@monstermunchkin I don't have access to my machine right now, but here is the custom settings I used in my LXD preseed to setup the storage pool : 

```YAML
lxd:
  preseed: |
    # - Storage pools -
    storage_pools:
    - name: default
      driver: zfs
      description: "Default storage pool for instances"
      config:
        source: /dev/nvme0n1
        zfs.pool_name: lxd
        volume.zfs.block_mode: true
        volume.zfs.blocksize: 32KiB
```

**Comment by monstermunchkin** [comment]
Looking through the logs, two lines caught my eye. When creating v1:
```
time="2023-07-24T10:44:43Z" level=debug msg="Increasing volume size" allowUnsafeResize=true dstPath=/dev/zvol/lxd/images/af709807b8995ab6c284179e989cb967210e406f632b5421ade19c0b453bad2f.block imageFile=/var/snap/lxd/common/lxd/images/af709807b8995ab6c284179e989cb967210e406f632b5421ade19c0b453bad2f imgPath=/var/snap/lxd/common/lxd/images/lxd_image_unpack_3549801805/rootfs.img newSize=34359738368 oldSize=10737418240
```

And when creating the others:
```
time="2023-07-24T10:46:42Z" level=debug msg="Renaming deleted cached image volume so that regeneration is used" driver=zfs fingerprint=af709807b8995ab6c284179e989cb967210e406f632b5421ade19c0b453bad2f pool=default
```

I don't see these lines when trying to reproduce the issue.

**Comment by f-bn** [comment]
Here is my complete LXD preseed if that can helps : 

```
# - LXD -
lxd:
  preseed: |
    # - Daemon settings -
    config:
      core.https_address: 192.168.144.3:8443
      core.metrics_address: 127.0.0.1:9000
    # - Storage pools -
    storage_pools:
      - name: default
        driver: zfs
        description: "Default storage pool for instances"
        config:
          source: /dev/nvme0n1
          zfs.pool_name: lxd
          volume.zfs.block_mode: true
          volume.zfs.blocksize: 32KiB
      - name: volumes
        driver: lvm
        description: "Storage pool for instances data volumes"
        config:
          source: /dev/nvme1n1
          lvm.vg_name: lxd
          lvm.use_thinpool: false
          volume.block.filesystem: xfs
          volume.block.mount_options: "noatime"
    # - Networks -
    networks:
      - name: lxd-sbx
        type: bridge
        description: "Private network for sandbox environment"
        config:
          bridge.mode: standard
          dns.domain: sbx.homelab.lxd
          dns.mode: managed
          ipv4.address: 10.0.1.1/24
          ipv4.dhcp: true
          ipv4.dhcp.ranges: 10.0.1.10-10.0.1.254
          ipv4.dhcp.expiry: 1h
          ipv4.nat: true
          ipv4.nat.address: 192.168.144.4
          ipv4.nat.order: before
          ipv4.firewall: false
          ipv6.address: none
          ipv6.firewall: false
      - name: lxd-k8s
        type: bridge
        description: "Private network for Kubernetes lab environment"
        config:
          bridge.mode: standard
          dns.domain: k8s.homelab.lxd
          dns.mode: managed
          ipv4.address: 10.0.2.1/26
          ipv4.dhcp: true
          ipv4.dhcp.ranges: 10.0.2.10-10.0.2.63
          ipv4.dhcp.expiry: 1h
          ipv4.nat: true
          ipv4.nat.address: 192.168.144.5
          ipv4.nat.order: before
          ipv4.firewall: false
          ipv6.address: none
          ipv6.firewall: false
    # - Projects -
    projects:
      - name: default
        description: "Default namespace (workloads disabled)"
        config:
          limits.instances: 0
          limits.cpu: 0
          limits.memory: 0
          limits.processes: 0
      - name: sandbox
        description: "Testing environment namespace"
        config:
          features.images: false
          features.profiles: true
          features.networks: false
          features.storage.volumes: true
          features.storage.buckets: true
          restricted: true
          restricted.backups: allow
          restricted.containers.nesting: allow
          restricted.containers.interception: allow
          restricted.containers.privilege: allow
          restricted.devices.disk: managed
          restricted.devices.proxy: allow
          restricted.devices.nic: managed
          restricted.snapshots: allow
          restricted.networks.access: lxd-sbx
      - name: k8s
        description: "Kubernetes lab namespace"
        config:
          features.images: false
          features.profiles: true
          features.networks: false
          features.storage.volumes: true
          features.storage.buckets: true
          restricted: true
          restricted.backups: allow
          restricted.containers.interception: allow
          restricted.containers.privilege: unprivileged
          restricted.devices.disk: managed
          restricted.devices.nic: managed
          restricted.snapshots: allow
          restricted.networks.access: lxd-k8s
 ````
