### ISSUE TITLE
long device names don't show up properly under /dev/disk/by-id

### ISSUE THREAD

**Issue by digitalsignalperson** [canonical/lxd#12152]
# Required information

 * Distribution: arch linux
 * Distribution version: rolling; uname -a `6.1.39-1-lts #1 SMP PREEMPT_DYNAMIC Wed, 19 Jul 2023 17:58:31 +0000 x86_64 GNU/Linux`
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.1.39-1lts
   * LXC version: 5.15
   * LXD version: 5.15
   * Storage backend in use: zfs
  
# Issue description

I'm creating block devices with `lxc storage volume create` and attaching them to a VM. 
- If the name is long like "disk-arch-gen-work" it ends up garbled or non-existant in /dev/disk/by-id
- If the name is short like "agwork" it appears as expected in /dev/disk/by-id

# Steps to reproduce

1. My default pool is ZFS
2. Create two volumes
```
lxc storage volume create default disk-arch-gen-work size=10GiB --type=block
lxc storage volume create default disk-arch-gen-usb size=4GiB --type=block
```
3. attach to a new VM
```
lxc init images:archlinux "$VMNAME" --vm -c security.secureboot=false -c limits.memory=16GiB -c limits.cpu=$(nproc)
lxc storage volume attach default disk-arch-gen-work "$VMNAME"
lxc storage volume attach default disk-arch-gen-usb "$VMNAME"
```
4. Start VM and check names under /dev/disk/by-id
```
lxc start "$VMNAME"
lxc exec "$VMNAME" -- /bin/ls -l /dev/disk/by-id
```
The output is:
```
total 0
lrwxrwxrwx 1 root root  9 Aug 14 07:16 scsi-0QEMU_QEMU_HARDDISK_lxd_disk--arch--gen- -> ../../sdb
lrwxrwxrwx 1 root root  9 Aug 14 07:16 scsi-0QEMU_QEMU_HARDDISK_lxd_root -> ../../sda
lrwxrwxrwx 1 root root 10 Aug 14 07:16 scsi-0QEMU_QEMU_HARDDISK_lxd_root-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Aug 14 07:16 scsi-0QEMU_QEMU_HARDDISK_lxd_root-part2 -> ../../sda2
```
We get one one mangled "...disk--arch--gen-" that is wrong and cutoff.  If I look at lsblk I can see both the attached devices, unlabeled, under sdb and sdc.

Trying to shorten the name like this doesn't work (which the docs suggested [here](https://documentation.ubuntu.com/lxd/en/latest/howto/storage_volumes/#:~:text=If%20you%20want%20to%20use%20a%20different%20device%20name%2C%20you%20can%20add%20it%20to%20the%20command%3A)):
```
lxc storage volume attach default disk-arch-gen-work "$VMNAME" agwork
Error: Failed add validation for device "disk-arch-gen-work": Custom block volumes cannot have a path defined
```

If I delete everything and start again, but make short names instead like this

```
lxc storage volume create default agwork size=10GiB --type=block
lxc storage volume create default agusb size=4GiB --type=block
```
then the `lxc exec "$VMNAME" -- /bin/ls -l /dev/disk/by-id` output is 
```
total 0
lrwxrwxrwx 1 root root  9 Aug 14 07:22 scsi-0QEMU_QEMU_HARDDISK_lxd_agusb -> ../../sdb
lrwxrwxrwx 1 root root  9 Aug 14 07:22 scsi-0QEMU_QEMU_HARDDISK_lxd_agwork -> ../../sdc
lrwxrwxrwx 1 root root  9 Aug 14 07:22 scsi-0QEMU_QEMU_HARDDISK_lxd_root -> ../../sda
lrwxrwxrwx 1 root root 10 Aug 14 07:22 scsi-0QEMU_QEMU_HARDDISK_lxd_root-part1 -> ../../sda1
lrwxrwxrwx 1 root root 10 Aug 14 07:22 scsi-0QEMU_QEMU_HARDDISK_lxd_root-part2 -> ../../sda2
```
Now we have the nice "..._agusb" and "..._agwork" names under /dev/disk/by-id as expected.

# Information to attach

 - [x] Any relevant kernel output (`dmesg`)
 - [x] Container log (`lxc info NAME --show-log`)
 - [x] Container configuration (`lxc config show NAME --expanded`)
 - [x] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

Some dmesg output from the VM
```
[    1.183158] sd 6:0:0:1: [sda] 20971520 512-byte logical blocks: (10.7 GB/10.0 GiB)
[    1.183212] sd 6:0:1:1: [sdb] 8388608 512-byte logical blocks: (4.29 GB/4.00 GiB)
[    1.183221] sd 6:0:0:1: [sda] Write Protect is off
[    1.183224] 9pnet: Installing 9P2000 support
[    1.183225] sd 6:0:0:1: [sda] Mode Sense: 63 00 00 08
[    1.183272] sd 6:0:1:1: [sdb] Write Protect is off
[    1.183275] sd 6:0:1:1: [sdb] Mode Sense: 63 00 00 08
[    1.183290] sd 6:0:2:1: Power-on or device reset occurred
[    1.183302] sd 6:0:0:1: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.183366] sd 6:0:2:1: [sdc] 20971520 512-byte logical blocks: (10.7 GB/10.0 GiB)
[    1.183393] sd 6:0:2:1: [sdc] Write Protect is off
[    1.183395] sd 6:0:2:1: [sdc] Mode Sense: 63 00 00 08
[    1.183439] sd 6:0:2:1: [sdc] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.183516] sd 6:0:1:1: [sdb] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    1.184277] sd 6:0:2:1: [sdc] Attached SCSI disk
[    1.184342] sd 6:0:1:1: [sdb] Attached SCSI disk
[    1.185418]  sda: sda1 sda2
[    1.185523] sd 6:0:0:1: [sda] Attached SCSI disk
```

lxc info arch-gen-vm --show-log
```
Name: arch-gen-vm
Status: RUNNING
Type: virtual-machine
Architecture: x86_64
PID: 2945638
Created: 2023/08/14 00:27 PDT
Last Used: 2023/08/14 00:27 PDT

Resources:
  Processes: 16
  Disk usage:
    root: 4.25MiB
  CPU usage:
    CPU usage (in seconds): 9
  Memory usage:
    Memory (current): 331.49MiB
  Network usage:
    enp5s0:
      Type: broadcast
      State: UP
      Host interface: tap83db779f
      MAC address: 00:16:3e:65:e8:f9
      MTU: 1500
      Bytes received: 12.88kB
      Bytes sent: 4.59kB
      Packets received: 63
      Packets sent: 48
      IP addresses:
        inet:  10.62.222.60/24 (global)
        inet6: fd42:2b0c:af1c:963e:216:3eff:fe65:e8f9/64 (global)
        inet6: fe80::216:3eff:fe65:e8f9/64 (link)
    lo:
      Type: loopback
      State: UP
      MTU: 65536
      Bytes received: 6.32kB
      Bytes sent: 6.32kB
      Packets received: 80
      Packets sent: 80
      IP addresses:
        inet:  127.0.0.1/8 (local)
        inet6: ::1/128 (local)

Log:

```

lxc config show "$VMNAME" --expanded
```
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Archlinux current amd64 (20230813_04:18)
  image.os: Archlinux
  image.release: current
  image.requirements.secureboot: "false"
  image.serial: "20230813_04:18"
  image.type: disk-kvm.img
  image.variant: default
  limits.cpu: "16"
  limits.memory: 16GiB
  security.secureboot: "false"
  volatile.base_image: 785404235b064acd527bac25d21fe76fdc79ea943e3fc2e8c66f691ba362c6d5
  volatile.cloud-init.instance-id: 11a33e06-dc6c-44ce-b3e0-d3009d055483
  volatile.eth0.host_name: tap83db779f
  volatile.eth0.hwaddr: 00:16:3e:65:e8:f9
  volatile.last_state.power: RUNNING
  volatile.uuid: 40532d25-18ed-4f8f-ae5b-a9c8661dfb80
  volatile.uuid.generation: 40532d25-18ed-4f8f-ae5b-a9c8661dfb80
  volatile.vsock_id: "20"
devices:
  disk-arch-gen-usb:
    pool: default
    source: disk-arch-gen-usb
    type: disk
  disk-arch-gen-work:
    pool: default
    source: disk-arch-gen-work
    type: disk
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

/var/log/lxd/lxd.log - nothing while reproducing this

Also after doing a lot of this creating and destroying to get info for this issue
```
lxc storage volume create default disk-arch-gen-work size=10GiB --type=block
lxc storage volume create default disk-arch-gen-usb size=4GiB --type=block
lxc storage volume delete default disk-arch-gen-work
lxc storage volume delete default disk-arch-gen-usb
lxc storage volume create default agwork size=10GiB --type=block
lxc storage volume create default agusb size=4GiB --type=block
lxc storage volume delete default agwork
lxc storage volume delete default agusb
```
I can no longer create the volumes
```
lxc storage volume create default agwork size=10GiB --type=block
Error: Failed locating zvol for deactivation: Could not locate a zvol for rpoolx/LOCAL/lxd/custom/default_agwork
```
