### ISSUE TITLE
Issues with member evacuation when using auto mode

### ISSUE THREAD

**Issue by MusicDin** [canonical/lxd#12174]
There appear to be inconsistencies between evacuating an instance created using a profile and one initialized with the same configuration directly.

# Steps to reproduce

Cluster is deployed on top of 3 virtual machines and is running LXD version `5.16`.

Profile `default`:
```yaml
config: {}
description: Default LXD profile
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by: []
```

Profile `empty`:
```yaml
config: {}
description: ""
devices: {}
name: empty
used_by: []
```

Network `lxdbr0`:
```yaml
config:
  ipv4.address: 10.141.159.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:90d9:c63:4199::1/64
  ipv6.nat: "true"
description: ""
name: lxdbr0
type: bridge
used_by: []
managed: true
status: Created
locations:
- cls-1
- cls-2
- cls-3
```

Create two instances on `cls-1`: one using the default profile and another by defining the storage and network via command flags.:
```
$ lxc launch ubuntu:22.04 c1 --target cls-1 --profile default
$ lxc launch ubuntu:22.04 c2 --target cls-1 --profile empty --storage default --network lxdbr0
$ lxc list

+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| NAME |  STATE  |         IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS | LOCATION |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| c1   | RUNNING | 10.222.237.91 (eth0) | fd42:9d34:ca94:de71:216:3eff:fe54:32c8 (eth0) | CONTAINER | 0         | cls-1    |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| c2   | RUNNING | 10.222.237.38 (eth0) | fd42:9d34:ca94:de71:216:3eff:fe38:7f6c (eth0) | CONTAINER | 0         | cls-1    |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
```

Evacuate cluster member `cls-1`:
```
$ lxc cluster evacuate cls-1 --force
$ lxc list

+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| NAME |  STATE  |         IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS | LOCATION |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| c1   | STOPPED |                      |                                               | CONTAINER | 0         | cls-1    |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
| c2   | RUNNING | 10.222.237.38 (eth0) | fd42:9d34:ca94:de71:216:3eff:fe38:7f6c (eth0) | CONTAINER | 0         | cls-2    |
+------+---------+----------------------+-----------------------------------------------+-----------+-----------+----------+
```

Instance `c1` results in `STOPPED` state. This happens only when evacuation is done using `--action auto` and a profile applied to the instance.

---

## Debugging

I've added some logs in [lxd/instance/driver_common.go#canMigrate()](https://github.com/canonical/lxd/blob/8278714c6694491384b2517230f58f13a3e5d7f8/lxd/instance/drivers/driver_common.go#L1091-L1100):

```go
for deviceName, rawConfig := range d.ExpandedDevices() {
	dev, err := device.New(inst, d.state, deviceName, rawConfig, volatileGet, volatileSet)
	if err != nil {
		logger.Warnf("Instance %q cannot be auto migrated. Device %q stopped the migration due to an error: %v", inst.Name(), dev.Name(), err)
		return false, false
	}

	if !dev.CanMigrate() {
		logger.Warnf("Instance %q cannot be auto migrated. Device %q cannot be migrated. Device config: %+v", inst.Name(), dev.Name(), dev.Config())
		return false, false
	}

	logger.Warnf("[Instance %q] Device %q can be migrated. Device config: %+v", inst.Name(), dev.Name(), dev.Config())
}
```

And during evacuation the following output is intercepted:
```
Instance "c1" cannot be auto migrated. Device "eth0" cannot be migrated. 
Device config: map[nictype:bridged parent:lxdbr0 type:nic]

[Instance "c2"] Device "eth0" can be migrated. 
Device config: map[name:eth0 network:lxdbr0 parent:lxdbr0 type:nic]
```

So, the evacuation fails for `c1` because when calling [`dev.CanMigrate()`](https://github.com/canonical/lxd/blob/8278714c6694491384b2517230f58f13a3e5d7f8/lxd/device/nic_bridged.go#L55-L58) for bridged network device `eth0`, the device's config does not contain field `network`. 

---

I assume this is not expected behavior? 

In any case, I propose that we at least add a warning to the log that would indicate why the instance has failed the evacuation.

Any thoughts?

**Comment by tomponline** [comment]
Can you show the `lxc config show <instance>` with and without `--expanded` flag for each instance please.

**Comment by MusicDin** [comment]
Config for instance `c1`:
```yaml
# lxc config show c1
#
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 22.04 LTS amd64 (release) (20230815)
  image.label: release
  image.os: ubuntu
  image.release: jammy
  image.serial: "20230815"
  image.type: squashfs
  image.version: "22.04"
  volatile.base_image: ebed156c664de5e9f86c1a2eee7b61031af072af35e90048d2944b3e485f8303
  volatile.cloud-init.instance-id: c2c7be4b-183a-48b7-aa43-cfd781fc476c
  volatile.eth0.host_name: veth68d2e71a
  volatile.eth0.hwaddr: 00:16:3e:54:32:c8
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: 72ab3851-0f43-48f3-ad89-3e27b4858008
  volatile.uuid.generation: 72ab3851-0f43-48f3-ad89-3e27b4858008
devices: {}
ephemeral: false
profiles:
- default
stateful: false
description: ""

# lxc config show c1 --expanded
#
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 22.04 LTS amd64 (release) (20230815)
  image.label: release
  image.os: ubuntu
  image.release: jammy
  image.serial: "20230815"
  image.type: squashfs
  image.version: "22.04"
  volatile.base_image: ebed156c664de5e9f86c1a2eee7b61031af072af35e90048d2944b3e485f8303
  volatile.cloud-init.instance-id: c2c7be4b-183a-48b7-aa43-cfd781fc476c
  volatile.eth0.host_name: veth68d2e71a
  volatile.eth0.hwaddr: 00:16:3e:54:32:c8
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: 72ab3851-0f43-48f3-ad89-3e27b4858008
  volatile.uuid.generation: 72ab3851-0f43-48f3-ad89-3e27b4858008
devices:
  eth0:
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

Config for instance `c2`:
```yaml
# lxc config show c2
#
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 22.04 LTS amd64 (release) (20230815)
  image.label: release
  image.os: ubuntu
  image.release: jammy
  image.serial: "20230815"
  image.type: squashfs
  image.version: "22.04"
  volatile.base_image: ebed156c664de5e9f86c1a2eee7b61031af072af35e90048d2944b3e485f8303
  volatile.cloud-init.instance-id: 197eaabe-fe17-4ac7-87a5-4f5097d483f6
  volatile.eth0.host_name: veth142c3cb2
  volatile.eth0.hwaddr: 00:16:3e:38:7f:6c
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: efb3c941-8bbc-4da9-a9b4-b21d06ffc3d8
  volatile.uuid.generation: efb3c941-8bbc-4da9-a9b4-b21d06ffc3d8
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- empty
stateful: false
description: ""

# lxc config show c2 --expanded
#
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 22.04 LTS amd64 (release) (20230815)
  image.label: release
  image.os: ubuntu
  image.release: jammy
  image.serial: "20230815"
  image.type: squashfs
  image.version: "22.04"
  volatile.base_image: ebed156c664de5e9f86c1a2eee7b61031af072af35e90048d2944b3e485f8303
  volatile.cloud-init.instance-id: 197eaabe-fe17-4ac7-87a5-4f5097d483f6
  volatile.eth0.host_name: veth142c3cb2
  volatile.eth0.hwaddr: 00:16:3e:38:7f:6c
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: efb3c941-8bbc-4da9-a9b4-b21d06ffc3d8
  volatile.uuid.generation: efb3c941-8bbc-4da9-a9b4-b21d06ffc3d8
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- empty
stateful: false
description: ""
```
