### ISSUE TITLE
NIC acceleration configuration method prevents the use of bonds and VF-LAG (OVN)

### ISSUE THREAD

**Issue by fnordahl** [canonical/lxd#12233]
LXD supports configuring NIC acceleration for cards that support switchdev mode and OVS hardware offload.

However, the current method of discovering which PF to allocate resources from prevents putting the PFs in a bond and making use of the VF-LAG feature:
https://github.com/canonical/lxd/blob/227bc5cd75ebf2ba7b6c881f209ed5c2e6640f9b/lxd/network/network_utils_sriov.go#L385-L387

The current functionality is documented here:
https://github.com/canonical/lxd/blob/227bc5cd75ebf2ba7b6c881f209ed5c2e6640f9b/doc/reference/devices_nic.md?plain=1#L209-L216

We need to replace this with some sort of configuration option that can be set per target when in a cluster.

The expected way to use this would at a high level be:
* Let's say `enp9s0f0np0` and `enp9s0f1np1` are PFs of a switchdev capable card.
* Create bond0 with `enp9s0f0np0` and `enp9s0f1np1`
* Create OVS bridge `br-bond0` that will be used both for host connectivity, external networking for LXD instances and VF resources.

The netplan configuration could be expressed as this:
```yaml
network:
    bonds:
        bond0:
            interfaces:
            - enp9s0f0np0
            - enp9s0f1np1
            macaddress: 08:c0:eb:81:6b:78
            parameters:
                mode: 802.3ad
                ...
    bridges:
        br-bond0:
            addresses:
            - 192.0.2.10/24
            interfaces:
            - bond0
            macaddress: 08:c0:eb:81:6b:78
            openvswitch: {}
    ethernets:
        enp9s0f0np0:
            match:
                macaddress: 08:c0:eb:81:6b:78
            set-name: enp9s0f0np0
            virtual-function-count: 32
            embedded-switch-mode: switchdev
            delay-virtual-functions-rebind: true
        enp9s0f1np1:
            match:
                macaddress: 08:c0:eb:81:6b:79
            set-name: enp9s0f1np1
            virtual-function-count: 32
            embedded-switch-mode: switchdev
            delay-virtual-functions-rebind: true
```
