### ISSUE TITLE
`loki.types` config not shown

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#12270]
`loki.types` is omit from the config list and `get`'ing it doesn't work:

```
# lxc config set loki.api.url=http://10.76.66.141:3100
# lxc config set loki.labels=sdeziel
# lxc config set loki.types="lifecycle,logging"
# lxc config get loki.types

# lxc config show
config:
  loki.api.url: http://10.76.66.141:3100
  loki.labels: sdeziel
```

Version info:

```
# snap list lxd
Name  Version       Rev    Tracking       Publisher   Notes
lxd   5.17-e5ead86  25505  latest/stable  canonical✓  -
```

**Comment by monstermunchkin** [comment]
I don't believe this is a bug. If the default value is set (in this case `lifecycle,logging`) it is not shown in `lxc config show`. The same applies if you set `loki.loglevel` to `info`. As that's the default value, it won't be shown.

**Comment by monstermunchkin** [comment]
For the future, perhaps we could add an `--all` flag to `lxc config show` which shows all values, including the default values.

**Comment by tomponline** [comment]
@monstermunchkin thanks, can you show me where in the lxd code this happens? I seem to remember the way the global server config behaves is somewhat different to the way the rest of the config behaves, and is possible something we should address in LXD 6.0 to make it consistent.

**Comment by simondeziel** [comment]
> I don't believe this is a bug. If the default value is set (in this case `lifecycle,logging`) it is not shown in `lxc config show`. The same applies if you set `loki.loglevel` to `info`. As that's the default value, it won't be shown.

Oh, I hadn't realize that, it make sense indeed. I just checked and setting to `lifecycle` or `logging` alone makes it appear:

```
# lxc config set loki.types="logging"
root@lxd-loki:~# lxc config show
config:
  loki.api.url: http://10.76.66.141:3100
  loki.labels: sdeziel
  loki.types: logging
```

So I'm OK with closing this as an ID-10T error :)
