### ISSUE TITLE
Duplicate used by entry in storage pool

### ISSUE THREAD

**Issue by edlerd** [canonical/lxd#12335]
# Required information

   * LXD version: 5.18

# Issue description

When an instance or profile references a storage pool twice (i.e. as a root storage and using a custom volume), the API response for the storage pool will contain two references to the instance or profile in the `used_by` section.

The used by list should be deduplicated.

The duplication in `used_by` lists might appear on other entities as well.

# Steps to reproduce

 1. Create a storage pool "big-pool"
 2. Create a custom volume named "big-volume" in that pool
 3. Create a profile "volume-profile" referencing 1 and 2 like below
  ```
config: {}
description: ''
devices:
  big-volume:
    path: /shared
    pool: big-pool
    source: big-volume
    type: disk
  root:
    path: /
    pool: big-pool
    type: disk
name: volume-profile
```
 5. Query the storage pool via `GET` of the API route `/1.0/storage-pools/big-pool`.
 6. The response contains two identical entries pointing to "volume-profile" in the  `metadata.used_by` section.
