### ISSUE TITLE
`lxc export --instance-only` becomes useless (snapshout count check during import)

### ISSUE THREAD

**Issue by qupfer** [canonical/lxd#12370]
# Required information

 * Distribution: Ubuntu 
 * Distribution version: 23.04
 * The output of "lxc info":
 ``` 
driver: lxc | qemu
  driver_version: 5.0.3 | 8.0.4
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 6.2.0-34-generic
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "23.04"
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: otpe.de
  server_pid: 988
  server_version: "5.18"
  storage: btrfs
  storage_version: 5.16.2
  storage_supported_drivers:
  - name: cephobject
    version: 17.2.6
    remote: true
  - name: dir
    version: "1"
    remote: false
  - name: lvm
    version: 2.03.11(2) (2021-01-08) / 1.02.175 (2021-01-08) / 4.47.0
    remote: false
  - name: zfs
    version: 2.1.9-2ubuntu1.1
    remote: false
  - name: btrfs

````

# Issue description

The `--instance-only` option becomes useless since a few version as the resulting archive is not importable if a snapshot exist due export time.
If no snapshot exist,  `--instance-only` makes no sense either. 

# Steps to reproduce

 1. `lxc launch images:alpine/3.18 c1`
 2. `lxc snapshot c1`
 3. `lxc export --instance-only c1`
 4. `lxc stop c1`
 5. `lxc rename c1 c2`
 6. `lxc import c1.tar.gz`

# Information to attach
Error message due step 6:
``` 
Error: Failed importing backup: Failed checking snapshots: Snapshot count in backup config and storage device are different: Backup snapshots mismatch
``` 

I think, `lxc export` should write a snapshot count of 0 to the metadata if `--instance-only` is used.
