### ISSUE TITLE
Dualstack BGP does not work

### ISSUE THREAD

**Issue by gurubert** [canonical/lxd#12547]
Hi,

I am trying to setup microcloud with OVN networking and BGP to the outside world.
I get the connections to the external BGP routers but the updates sent by the LXD bgp daemon do not have the correct Ip family set.

If core.bgp_address is an IPv4 address (A.B.C.D) the IPv6 routes are updated with a nexthop of ::ffff:A.B.C.D which the receiving BGP routers reject as wrong family.

If core.bgp_address is an IPv6 address the IPv4 routes are updated with this IPv6 address as nexthop, which again the receiving BGP routers reject as wrong family.

How do i configure the LXD bgp daemon to talk IPv4 and IPv6 in parallel?

**Comment by tomponline** [comment]
I've moved this over to LXD repo as it is specific to LXD and not MicroCloud.

**Comment by tomponline** [comment]
@nmezhenskyi hey, as you're working in the area of BGP in LXD currently, I wondered if you could have a look at this issue please?

**Comment by nmezhenskyi** [comment]
I was able to reproduce the issue with the LXD host and a VM. The host LXD has BGP enabled and is advertising routes to the VM running BIRD. The host and the VM have different ASNs to create an external BGP session.

**Reproducer:**

1. Create a network bridge on the host (`lxdbr0` will do).
2. Create one or more VMs to run BIRD and act as external BGP peers to the host LXD.
     I.e.: `lxc init ubuntu:24.04 bird1 --vm --device root,size=20GiB --config limits.cpu=2 --config limits.memory=8GiB`
3. Attach the network bridge to VM(s) (`lxdbr0` should be attached already).
4. Install and configure BIRD on the VM(s) to establish IPv4 BGP session with the host LXD.
5. Add BGP peers to the host LXD:
    ```
     lxc network set lxdbr0 bgp.peers.bird1.address=<VM_IPv4>
     lxc network set lxdbr0 bgp.peers.bird1.asn=<VM_ASN>
    ```
6. Disable nat on the bridge, so that host can advertise ipv4.address and ipv6.address subnets:
   ```
   lxc network set lxdbr0 ipv4.nat=false
   lxc network set lxdbr0 ipv6.nat=false
   ```
7. Start BGP listener on the host LXD:
   ```
   lxc config set core.bgp_address=<BRIDGE_IPv4>:179
   lxc config set core.bgp_asn=<HOST_ASN>
   lxc config set core.bgp_routerid=<BRIDGE_IPv4>
   ```
8. BIRD logs inside of a VM should produce something like this:
   ```
   2025-03-21 17:43:30.570 <RMT> lxd_bgp_ipv4: Invalid NEXT_HOP attribute - mismatched address family (10.97.181.1 for ipv6)
   2025-03-21 17:43:30.570 <RMT> lxd_bgp_ipv4: Invalid route fd42:3048:780b:f58d::/64 withdrawn
   ```

This is `lxdbr0` config on the host:
```
name: lxdbr0
description: ""
type: bridge
managed: true
status: Created
config:
  bgp.peers.bird1.address: 10.97.181.10
  bgp.peers.bird1.asn: "65001"
  bgp.peers.bird2.address: 10.97.181.20
  bgp.peers.bird2.asn: "65002"
  ipv4.address: 10.97.181.1/24
  ipv4.nat: "false"
  ipv6.address: fd42:3048:780b:f58d::1/64
  ipv6.nat: "false"
used_by:
- /1.0/instances/bird1
- /1.0/instances/bird2
- /1.0/profiles/default
locations:
- none
```

This is LXD config on the host:
```
config:
  core.bgp_address: 10.97.181.1:179
  core.bgp_asn: "65000"
  core.bgp_routerid: 10.97.181.1
```

This is the VM's BIRD config `/etc/bird/bird.conf`:
```
log "/var/log/bird.log" { debug, trace, info, remote, warning, error, auth, fatal, bug };

router id 10.97.181.10;

protocol device {
}

protocol bgp lxd_bgp_ipv4 {
  neighbor 10.97.181.1 as 65000;
  local as 65001; 
  source address 10.97.181.10;
  ipv4 { import all; export all; };
  ipv6 { import all; export all; };
}
```

**Comment by nmezhenskyi** [comment]
@tomponline  From my understanding, the conventional approach is to exchange only IPv4 prefixes over an IPv4 external BGP session and only IPv6 prefixes over an IPv6 eBGP session to avoid the problem of mixing the prefixes. LXD currently does not allow to establish parallel IPv4 and IPv6 sessions. Only one session can be active and it is not possible to restrict the family of prefixes to share. We always enable both IPv4 and IPv6 [here](https://github.com/canonical/lxd/blob/15dd0ae0f41673b989a9ecd1b65eb8c69b8ddc43/lxd/bgp/server.go#L97).  

Should I look into implementing the support for parallel IPv4 and IPv6 sessions?

The current issue is not a problem for internal BGP sessions sharing the same ASN, because they do not update the next hop address. But it seems that external BGP is a more common model for data center deployments.

**Comment by nmezhenskyi** [comment]
I did some more digging into this issue. It should be possible to exchange both IPv4 and IPv6 prefixes correctly over a single session after all. It requires configuring routing policies to modify the next hop address to a correct family. Currently we allow manually changing `bgp.ipv4.nexthop` and `bgp.ipv6.nexthop` attributes on a bridge interface.  

I was able to make my example work by establishing IPv6 session with peers instead of IPv4, and by changing the `bgp.ipv4.nexthop` attribute of `lxdbr0` to `::ffff:a61:b501` (translated IPv4 address of `lxdbr0` to IPv6 representation).

Now, BIRD peers are able to receive both IPv6 and IPv4 correctly.  

Updated config for `lxdbr0`:  
```
lxc network show lxdbr0

name: lxdbr0
description: ""
type: bridge
managed: true
status: Created
config:
  bgp.ipv4.nexthop: ::ffff:a61:b501
  bgp.peers.bird1.address: fd42:3048:780b:f58d::10
  bgp.peers.bird1.asn: "65001"
  bgp.peers.bird2.address: fd42:3048:780b:f58d::20
  bgp.peers.bird2.asn: "65002"
  ipv4.address: 10.97.181.1/24
  ipv4.nat: "false"
  ipv6.address: fd42:3048:780b:f58d::1/64
  ipv6.nat: "false"
```

I also added a network forward for `lxdbr0` to see if it will be advertised correctly (it is).
```
lxc network forward list lxdbr0

+----------------+-------------+------------------------+-------+
| LISTEN ADDRESS | DESCRIPTION | DEFAULT TARGET ADDRESS | PORTS |
+----------------+-------------+------------------------+-------+
| 198.51.100.1   |             |                        | 0     |
+----------------+-------------+------------------------+-------+
```

BGP config on the host:  
```
lxc config show

config:
  core.bgp_address: fd42:3048:780b:f58d::1
  core.bgp_asn: "65000"
  core.bgp_routerid: 10.97.181.1
```

Updated VM's bird config `/etc/bird/bird.conf`:
```
log "/var/log/bird.log" { debug, trace, info, remote, warning, error, auth, fatal, bug };

router id 10.97.181.10;

protocol device {
}

protocol bgp lxd_bgp_ipv4 {
  neighbor fd42:3048:780b:f58d::1 as 65000;
  local as 65001;
  source address fd42:3048:780b:f58d::10;
  ipv4 { import all; export all; };
  ipv6 { import all; export all; };
}
```

Here are the routes that bird VM sees:  
```
birdc show route

BIRD 2.14 ready.
Table master4:
198.51.100.1/32      unicast [lxd_bgp_ipv4 21:28:26.387 from fd42:3048:780b:f58d::1] * (100) [AS65000i]
	via 10.97.181.1 on enp5s0
10.97.181.0/24       unicast [lxd_bgp_ipv4 21:28:26.387 from fd42:3048:780b:f58d::1] * (100) [AS65000i]
	via 10.97.181.1 on enp5s0

Table master6:
fd42:3048:780b:f58d::/64 unicast [lxd_bgp_ipv4 21:28:26.387] * (100) [AS65000i]
	via fd42:3048:780b:f58d::1 on enp5s0
```

**Comment by nmezhenskyi** [comment]
However, LXD does not allow setting `bgp.ipv4.nexthop` and `bgp.ipv6.nexthop` for physical networks. So, this approach won't work in the case of OVN with physical network as uplink.

**Comment by nmezhenskyi** [comment]
Hi @gurubert ,

I tested Microcloud with OVN networking and exposed BGP to the outside world and it is working correctly. I did not encounter the issue you described.  

Here is my setup:  

> **_NOTE:_**  You can follow this [guide](https://canonical-microcloud.readthedocs-hosted.com/en/v2-edge/microcloud/tutorial/get_started/) to create a Microcloud cluster with OVN.  

On the host machine I created 3 VMs to form a Microcloud cluster and 1 container outside of the cluster.

On the host I have two bridge interfaces: `lxdbr0` and `microbr0`. `lxdbr0` is attached to each cluster VM as `enp5s0` to establish connectivity with the host. `microbr0` is used as uplink network for OVN and attached to each VM as `enp6s0`. `microbr0` is also attached to the outside container (c1) as `eth0`.

`lxcbr0` config:
```
lxc network show lxdbr0

name: lxdbr0
description: ""
type: bridge
managed: true
status: Created
config:
  ipv4.address: 10.251.3.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:1455:df94:cc97::1/64
  ipv6.dhcp.stateful: "true"
  ipv6.nat: "true"
used_by:
- /1.0/instances/micro1
- /1.0/instances/micro2
- /1.0/instances/micro3
- /1.0/profiles/default
locations:
- none
```

`microbr0` config:
```
lxc network show microbr0

name: microbr0
description: ""
type: bridge
managed: true
status: Created
config:
  ipv4.address: 10.22.7.1/24
  ipv4.nat: "false"
  ipv6.address: fd42:cc09:9260:e98a::1/64
  ipv6.nat: "false"
used_by:
- /1.0/instances/c1
- /1.0/instances/micro1
- /1.0/instances/micro2
- /1.0/instances/micro3
locations:
- none
```

> **_NOTE:_** It's important to set `ipv4.nat` and `ipv6.nat` to false on `microbr0`.

Cluster VMs have static IPs assigned to them:
- `micro1`: 10.251.3.50 (enp5s0) and fd42:1455:df94:cc97::50 (enp5s0)
- `micro2`: 10.251.3.60 (enp5s0) and fd42:1455:df94:cc97::60 (enp5s0)
- `micro3`: 10.251.3.70 (enp5s0) and fd42:1455:df94:cc97::70 (enp5s0)

Outside container has these static IPs:
- `c1`: 10.22.7.20 (eth0) and fd42:cc09:9260:e98a:216:3eff:fe94:f39e (eth0)

Networks inside of the `micro1` VM:
```
lxc network ls

+---------+----------+---------+---------------+---------------------------+-------------+---------+---------+
|  NAME   |   TYPE   | MANAGED |     IPV4      |           IPV6            | DESCRIPTION | USED BY |  STATE  |
+---------+----------+---------+---------------+---------------------------+-------------+---------+---------+
| UPLINK  | physical | YES     |               |                           |             | 1       | CREATED |
+---------+----------+---------+---------------+---------------------------+-------------+---------+---------+
| br-int  | bridge   | NO      |               |                           |             | 0       |         |
+---------+----------+---------+---------------+---------------------------+-------------+---------+---------+
| default | ovn      | YES     | 10.82.20.1/24 | fd42:31c9:50c7:633c::1/64 |             | 2       | CREATED |
+---------+----------+---------+---------------+---------------------------+-------------+---------+---------+
| enp5s0  | physical | NO      |               |                           |             | 0       |         |
+---------+----------+---------+---------------+---------------------------+-------------+---------+---------+
| enp6s0  | physical | NO      |               |                           |             | 1       |         |
+---------+----------+---------+---------------+---------------------------+-------------+---------+---------+
| lxdovn1 | bridge   | NO      |               |                           |             | 0       |         |
+---------+----------+---------+---------------+---------------------------+-------------+---------+---------+
```

```
lxc network show UPLINK

name: UPLINK
description: ""
type: physical
managed: true
status: Created
config:
  bgp.peers.c1.address: 10.22.7.20
  bgp.peers.c1.asn: "65001"
  dns.nameservers: 10.22.7.1,fd42:cc09:9260:e98a::1
  ipv4.gateway: 10.22.7.1/24
  ipv4.ovn.ranges: 10.22.7.100-10.22.7.254
  ipv4.routes: 10.82.20.0/24
  ipv6.gateway: fd42:cc09:9260:e98a::1/64
  ipv6.routes: fd42:31c9:50c7:633c::/64
  volatile.last_state.created: "false"
used_by:
- /1.0/networks/default
locations:
- micro3
- micro1
- micro2
```

```
lxc network show default

name: default
description: ""
type: ovn
managed: true
status: Created
config:
  bridge.mtu: "1442"
  ipv4.address: 10.82.20.1/24
  ipv4.nat: "false"
  ipv6.address: fd42:31c9:50c7:633c::1/64
  ipv6.nat: "false"
  network: UPLINK
  volatile.network.ipv4.address: 10.22.7.100
  volatile.network.ipv6.address: fd42:cc09:9260:e98a:216:3eff:fe54:7c69
used_by:
- /1.0/instances/c1
- /1.0/profiles/default
locations:
- micro3
- micro1
- micro2
```

Notice that `ipv4.nat` and `ipv6.nat` are disabled on the default (ovn) network to advertise `ipv4.address` and `ipv6.address` subnets. The BGP peers are added to the UPLINK network.

The BGP config on `micro1` VM looks like this:
```
core.bgp_address: 10.251.3.50
core.bgp_asn: "65000"
core.bgp_routerid: 10.251.3.50
```

```
lxc query /internal/testing/bgp

{
	"peers": [
		{
			"address": "10.22.7.20",
			"asn": 65001,
			"count": 1,
			"holdtime": 0,
			"password": ""
		}
	],
	"prefixes": [
		{
			"nexthop": "10.22.7.100",
			"owner": "network_2",
			"prefix": "10.82.20.0/24"
		},
		{
			"nexthop": "fd42:cc09:9260:e98a:216:3eff:fe54:7c69",
			"owner": "network_2",
			"prefix": "fd42:31c9:50c7:633c::/64"
		}
	],
	"server": {
		"address": "10.251.3.50",
		"asn": 65000,
		"router_id": "10.251.3.50",
		"running": true
	}
}
```

Here is the BIRD config on the outside container `c1`:
```
log "/var/log/bird.log" { debug, trace, info, remote, warning, error, auth, fatal, bug };

router id 10.22.7.20;

protocol device {
}

protocol direct {
        disabled;
        ipv4;
        ipv6;
}

protocol kernel {
        ipv4 { export all; };
	learn all;
}

protocol kernel {
        ipv6 { export all; };
	learn all;
}

protocol static {
        ipv4;
}

protocol bgp lxd_bgp_ipv4 {
  neighbor 10.251.3.50 as 65000;
  local as 65001;
  multihop;
  source address 10.22.7.20; 
  ipv4 { import all; export all; };
  ipv6 { import all; export all; };
}
```

> **_NOTE:_** It's important to specify `learn all;` in the `protocol kernel`.

Here is the route information from BIRD:
```
birdc show route

BIRD 2.14 ready.
Table master4:
0.0.0.0/0            unicast [kernel1 14:16:22.409] * (10)
	via 10.22.7.1 on eth0
10.82.20.0/24        unicast [lxd_bgp_ipv4 14:16:27.381 from 10.251.3.50] * (100/?) [AS65000i]
	via 10.22.7.100 on eth0
10.22.7.0/24         unicast [kernel1 14:16:22.409] * (10)
	dev eth0

Table master6:
::/0                 unicast [kernel2 14:16:22.409] * (10)
	via fe80::216:3eff:fed3:bbef on eth0
fd42:31c9:50c7:633c::/64 unicast [lxd_bgp_ipv4 14:16:27.381 from 10.251.3.50] * (100/?) [AS65000i]
	via fd42:cc09:9260:e98a:216:3eff:fe54:7c69 on eth0
fd42:cc09:9260:e98a::/64 unicast [kernel2 14:16:22.409] * (10)
	dev eth0
```
