### ISSUE TITLE
VM live migration never finishes for non-sharded storage between the nodes

### ISSUE THREAD

**Issue by gabrielmougard** [canonical/lxd#12765]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.5.0-14-generic
   * LXD version: 5.19-8635f82 (both for source and target machines)
   * Storage backend in use: Dir

# Issue description

I'm trying to do a live migration between machine A and machine B of a VM. There is no shared storage between  the VMs.

I created a profile called `stateful-vm` that I applied to my source VMs:
```
config:
  migration.stateful: "true"
description: Default LXD profile
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    size.state: 4GiB
    type: disk
name: stateful-vm
used_by:
- /1.0/instances/v1
- /1.0/instances/v2
- /1.0/instances/v3
```

I copied this profile to the target machine `lxc profile copy stateful-vm legion-laptop:stateful-vm` so that the VM can be instantiated on the other side with the profile.

The `size.state` parameter is `4GiB` which I think should be enough because the default VM memory is `1GiB` and I don't run any IOPS intensive work inside of it that would saturate a `.qcow2` file to register the live-writes during the migration.

Then, when attempting the live migration, the beginning seems fine (I see the bytes being transferred) but it'll never stop. Or to be more precise, the migration stops around `10GiB` being transferred and output the following error message:
`Error: Failed instance creation: Error transferring instance data: Failed migration on target: Failed restoring checkpoint from source: Monitor is disconnected`

 
# Steps to reproduce

 1. Create the `stateful-vm` profile as shown above and create a VM with it `lxc launch ubuntu:jammy v1 --vm --profile stateful-vm`
 2. Send the profileto the target : `lxc profile copy stateful-vm <TARGET>:stateful-vm`
 3. Start the migration: `lxc move v1 <TARGET>:v1` and witness the transfer size going much above the VM size to eventually fail.

# Information to attach

Here is the 'server log from the source' during the live migration:
[source.log](https://github.com/canonical/lxd/files/14024765/client.log)

And here is the 'server log from the target' of the target:
[target.log](https://github.com/canonical/lxd/files/14024773/server.log)
