### ISSUE TITLE
Bridge networks configured with external addresses expose resolving DNS service beyond network

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#13081]
LXD managed `bridge` networks provide a DNS resolution service (dnsmasq) intended only for instances connected to that network. However if the bridge's IP(s) are reachable from an externally connected network (because there is no firewall on the host) then the dnsmasq service is responding to DNS requests from external sources.

This is a problem because it could potentially be used in DNS amplification attacks.
Additionally internal instance names will also be resolvable, allowing potential discovery of instance IPs on the network.

LXD should configure dnsmasq in a way such that it doesn't respond to requests from outside of its network, or if thats not possible, then have it apply firewall rules to the same effect.

**Reproducer:**

Setup bridge network:
```
snap install lxd # 5.20
lxd init --auto
lxc network show lxdbr0
name: lxdbr0
description: ""
type: bridge
managed: true
status: Created
config:
  ipv4.address: 10.219.41.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:ba04:c433:c213::1/64
  ipv6.nat: "true"
```

Make bridge's IP subnets reachable from an "external" host connected to the LXD host on a different interface:

```
sudo ip r add 10.219.41.0/24 via <LXD Host IPv4>
sudo ip -6 r add fd42:ba04:c433:c213::/64 via <LXD Host IPv6>
dig @10.219.41.1 www.canonical.com # Resolves domain over IPv4 from external network
dig @fd42:ba04:c433:c213::1 www.canonical.com # Resolves domain over IPv6 from external network
```

In the meantime it is recommended that the LXD host is configured with a firewall to ensure external DNS requests do not make it to the managed bridge IP(s).
