### ISSUE TITLE
Ubuntu 24.04 AppArmor breaks pivot_root inside LXD containers

### ISSUE THREAD

**Issue by WereCatf** [canonical/lxd#13389]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 24.04
 * The output of "snap list --all lxd core20 core22 core24 snapd":
```
Name    Version         Rev    Tracking       Publisher   Notes
core22  20240408        1380   latest/stable  canonical✓  base
lxd     5.21.1-98dad8f  28323  5.21/stable/…  canonical✓  -
snapd   2.62            21465  latest/stable  canonical✓  snapd

```
 * The output of "lxc info" or if that fails:
   * Kernel version: 6.8.0-31-generic
   * LXC version: 5.21.1 LTS
   * LXD version: 5.21.1 LTS
   * Storage backend in use: Btrfs

# Issue description

Attempting to run e.g. `docker run hello-world` inside a container fails even with security.nesting enabled. Docker spits out the following error:
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error jailing process inside rootfs: pivot_root .: permission denied: unknown.
ERRO[0000] error waiting for container:
```
Dmesg shows an AppArmor error after attempting to run Docker:
`[  108.876252] audit: type=1400 audit(1714085791.618:236): apparmor="DENIED" operation="pivotroot" class="mount" namespace="root//lxd-testi_<var-snap-lxd-common-lxd>" profile="runc" name="/var/lib/docker/overlay2/9664d056286b3d0a93188f5fd09aba3fd82a6326c6ab7c9e3197a99996078eff/merged/" pid=2580 comm="runc:[2:INIT]" srcname="/var/lib/docker/overlay2/9664d056286b3d0a93188f5fd09aba3fd82a6326c6ab7c9e3197a99996078eff/merged/"`

# Steps to reproduce

 1. Install Ubuntu 24.04
 2. Set up LXD and launch a container with security.nesting=true
 3. Attempt to run a Docker container inside the container

**Comment by MusicDin** [comment]
Thanks. Quick link to previous discussion: https://discourse.ubuntu.com/t/ubuntu-24-04-broke-docker-inside-an-lxd-container/44499/6

**Comment by tomponline** [comment]
Most likely related to similar issue with Incus https://github.com/lxc/incus/issues/791#issuecomment-2083765381

**Comment by Yermo** [comment]
@tomponline I have reproduced this on my end here with Ubuntu 24.04, Ubuntu 22.04, and Ubuntu 18.04 container images.

**Comment by tomponline** [comment]
Does this fix it inside the container

ln -s /etc/apparmor.d/runc /etc/apparmor.d/disable/

**Comment by tomponline** [comment]
Also what does

`sudo cat /proc/sys/kernel/apparmor_restrict_unprivileged_userns`

Show both on the host and inside the container?

**Comment by Yermo** [comment]
```
root@openMapTiles1:~# ln -s /etc/apparmor.d/runc /etc/apparmor.d/disable/
root@openMapTiles1:~# docker run hello-world
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "proc" to rootfs at "/proc": mount proc:/proc (via /proc/self/fd/6), flags: 0xe: permission denied: unknown.
```
On the host:

```
root@mapmaker:~# sudo cat /proc/sys/kernel/apparmor_restrict_unprivileged_userns
0
```

In the container:

```
root@openMapTiles1:~# sudo cat /proc/sys/kernel/apparmor_restrict_unprivileged_userns
0
```

**Comment by tomponline** [comment]
What do you see in dmesg re apparmor after that?

**Comment by simondeziel** [comment]
After creating the symlink to disable the runc profile, you also need to unload the profile for this to take effect:

```
# ln -s /etc/apparmor.d/runc /etc/apparmor.d/disable/
# apparmor_parser -R  /etc/apparmor.d/runc
```

Rebooting the instance might also achieve the same.

**Comment by Yermo** [comment]
@tomponline In the system container I re-ran docker hello world while running sudo dmesg -w on the host. No messages were output.

**Comment by WereCatf** [comment]
> ```
> [345597.737544] audit: type=1400 audit(1715198413.326:236): apparmor="DENIED" operation="mount" class="mount" info="failed flags match" error=-13 profile="lxd-testContainer_</var/snap/lxd/common/lxd>" name="/var/lib/docker/overlay2/192f7cdf370b0c1e16733b8276c51a292c414f85832286038e07c7e938013005/merged/proc/" pid=873797 comm="runc:[2:INIT]" fstype="proc" srcname="proc" flags="rw, nosuid, nodev, noexec"
> ```
> 
> After setting the symlink and restarting the container no messages are output in dmesg -w however docker generates the same error as before.

You say no messages are output in dmesg, but there is actually a differently worded error in your log: Apparmor denied mount-operation from runc.

**Comment by Yermo** [comment]
@WereCatf Correct. The messages are generated before the symlink is added and the container restarted. After that no more messages are generated.

**Comment by mihalicyn** [comment]
Hi @WereCatf 

Please can you show `lxc config show <your_ct_name> -e`?

**Comment by WereCatf** [comment]
> Hi @WereCatf
> 
> Please can you show `lxc config show <your_ct_name> -e`?

I'm not sure why you want that as I stated the steps for recreating the issue, but here are two different containers with Ubuntu 23.10 and 24.04 on a 24.04 host:
```
nita@ubuvm:~$ lxc config show test -e
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 23.10 amd64 (release) (20240514)
  image.label: release
  image.os: ubuntu
  image.release: mantic
  image.serial: "20240514"
  image.type: squashfs
  image.version: "23.10"
  security.nesting: "true"
  volatile.base_image: 7843f1211e7b93e7254197bff3d69d13950a46f3352be98aacbebc52b5665c4b
  volatile.cloud-init.instance-id: 774764b2-2530-41e9-b54c-482d4e09d913
  volatile.eth0.host_name: veth853c1bcb
  volatile.eth0.hwaddr: 00:16:3e:7f:b7:f8
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 5ed1ce54-03c2-4b91-a44a-43d34d6eba0a
  volatile.uuid.generation: 5ed1ce54-03c2-4b91-a44a-43d34d6eba0a
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

```
nita@ubuvm:~$ lxc config show test2404 -e
architecture: x86_64
config:
  image.architecture: amd64
  image.description: ubuntu 24.04 LTS amd64 (release) (20240423)
  image.label: release
  image.os: ubuntu
  image.release: noble
  image.serial: "20240423"
  image.type: squashfs
  image.version: "24.04"
  security.nesting: "true"
  volatile.base_image: c9fba5728bfe168aa73084b94deab3dd3a1e349b5f7e0b5e5a8e945899cb0378
  volatile.cloud-init.instance-id: bb8fa7ea-20e1-4a7d-a9a0-46ac94f7b098
  volatile.eth0.host_name: veth2d8f10fd
  volatile.eth0.hwaddr: 00:16:3e:f8:02:d4
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 462d38ed-cd29-4072-be68-d814ece56ad4
  volatile.uuid.generation: 462d38ed-cd29-4072-be68-d814ece56ad4
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
