### ISSUE TITLE
OVN virtual router external addresses should show in `lxc network list-allocations` on the uplink network

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#13412]
Currently when listing IP allocations, one can see the external addresses allocated by network forwards and network load balancers from OVN networks on the uplink network, e.g.

```
lxc network list-allocations 
+------------------------------------------+---------------------------+-----------------+-------+------------------+
|                 USED BY                  |          ADDRESS          |      TYPE       |  NAT  | HARDWARE ADDRESS |
+------------------------------------------+---------------------------+-----------------+-------+------------------+
| /1.0/networks/lxdbr0                     | 10.199.41.1/24            | network         | true  |                  |
+------------------------------------------+---------------------------+-----------------+-------+------------------+
| /1.0/networks/lxdbr0                     | fd42:9542:ff80:fdb::1/64  | network         | true  |                  |
+------------------------------------------+---------------------------+-----------------+-------+------------------+
| /1.0/networks/ovn1                       | 10.179.69.1/24            | network         | true  |                  |
+------------------------------------------+---------------------------+-----------------+-------+------------------+
| /1.0/networks/ovn1                       | fd42:ca1d:2f42:bf38::1/64 | network         | true  |                  |
+------------------------------------------+---------------------------+-----------------+-------+------------------+
| /1.0/networks/ovn1/forwards/192.168.10.1 | 192.168.10.1/32           | network-forward | false |                  |
+------------------------------------------+---------------------------+-----------------+-------+------------------+
```

But the OVN networks also allocate external IPs on the uplink network for the external port of the virtual router:

```
lxc network show ovn1
name: ovn1
description: ""
type: ovn
managed: true
status: Created
config:
  bridge.mtu: "1500"
  ipv4.address: 10.179.69.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:ca1d:2f42:bf38::1/64
  ipv6.nat: "true"
  network: lxdbr0
  volatile.network.ipv4.address: 10.199.41.21
  volatile.network.ipv6.address: fd42:9542:ff80:fdb:216:3eff:fe51:3bd1
used_by: []
locations:
- none
```

We should display the `volatile.network.ipv4.address` and `volatile.network.ipv6.address` addresses in `lxc network list-allocations` as an allocation owned by the ovn network, i.e in this case `/1.0/networks/ovn1`.

The `type` displayed for these entries is debatable, but suggest we differentiate it from the `network` addresses by using something like `uplink`

Similarly, the `lxc network list-leases <uplink network>` command should so entries for OVN network forwards and load balancers connected to that network.
