### ISSUE TITLE
`lxd recover` loses the expiration dates of snapshots.

### ISSUE THREAD

**Issue by simondeziel** [canonical/lxd#13464]
I just went through a successful `lxd recover` which reimport my container and its snapshots from the intact zpool. Snapshots are taken on a schedule:

```sh
# lxc config show -e ganymede | grep snapshot
  snapshots.expiry: 3d
  snapshots.schedule: '@daily, @startup'
```

However, after `lxd recover` brought those snapshots back, they lost their `expires at` field:

```
# lxc info ganymede | sed -n '/^Snapshots:$/,$ p'
Snapshots:
+---------+----------------------+----------------------+----------+
|  NAME   |       TAKEN AT       |      EXPIRES AT      | STATEFUL |
+---------+----------------------+----------------------+----------+
| snap222 | 2024/05/07 05:28 UTC |                      | NO       |
+---------+----------------------+----------------------+----------+
| snap223 | 2024/05/08 05:28 UTC |                      | NO       |
+---------+----------------------+----------------------+----------+
| snap224 | 2024/05/09 05:28 UTC |                      | NO       |
+---------+----------------------+----------------------+----------+
| snap225 | 2024/05/09 22:21 UTC | 2024/05/12 22:21 UTC | NO       |
+---------+----------------------+----------------------+----------+
```

In the above, `snap225` was taken after the `lxd recover`.

However, the instance's `backup.yaml` should have had this information which is where it learned about the `taken at` field. That said, it seems the recovery have overwritten the `backup.yaml` with the bogus values now:

```
# LD_LIBRARY_PATH=/snap/lxd/current/lib/:/snap/lxd/current/lib/x86_64-linux-gnu/ nsenter --mount=/run/snapd/ns/lxd.mnt sed -n '/^volume_snapshots:$/,$ p' /var/snap/lxd/common/lxd/storage-pools/default/containers/ganymede/backup.yaml
volume_snapshots:
- name: snap222
  description: ""
  content_type: filesystem
  created_at: 0001-01-01T00:00:00Z
  expires_at: 0001-01-01T00:00:00Z
  config:
    volatile.uuid: a951c197-c11f-4fcc-a76e-ec575b99e305
- name: snap223
  description: ""
  content_type: filesystem
  created_at: 0001-01-01T00:00:00Z
  expires_at: 0001-01-01T00:00:00Z
  config:
    volatile.uuid: 2b8f7c0c-92da-4170-af35-c5033ec6b89c
- name: snap224
  description: ""
  content_type: filesystem
  created_at: 0001-01-01T00:00:00Z
  expires_at: 0001-01-01T00:00:00Z
  config:
    volatile.uuid: dba273a7-2980-46e4-afc3-ddb7ec617171
- name: snap225
  description: ""
  content_type: filesystem
  created_at: 2024-05-09T22:21:56.762923236Z
  expires_at: 0001-01-01T00:00:00Z
  config:
    volatile.uuid: 93c48d05-4de3-492b-8e6c-f3ce2e3e9c63
```

Additional information:

```sh
# snap list lxd
Name  Version         Rev    Tracking     Publisher   Notes
lxd   5.21.1-d46c406  28460  5.21/stable  canonical✓  -
```
