### ISSUE TITLE
In 5.21.2-ui-0.8.3 adding a boot.priority via YAML in the UI causes 'json: cannot unmarshal number into Go struct field ProfilePut.devices of type string'

### ISSUE THREAD

**Issue by stew3254** [canonical/lxd#14147]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "snap list --all lxd core20 core22 core24 snapd":
 ```
Name    Version         Rev    Tracking       Publisher   Notes
core20  20240705        2379   latest/stable  canonicalâ  base
core22  20240904        1621   latest/stable  canonicalâ  base
snapd   2.63            21759  latest/stable  canonicalâ  snapd
```
 * Kernel version: 5.15.0-122-generic
 * LXC version: Not sure
 * LXD version: 5.21.2-2f4ba6b
 * LXD UI version: 5.21.2-ui-0.8.3
 * Storage backend in use: dir

# Issue description

Since there is no option to set the boot priority on different devices in the 5.21 LXD UI, I attempted to add the boot.priority via the YAML configuration section of a profile. When I try to do that, I am given the error 'json: cannot unmarshal number into Go struct field ProfilePut.devices of type string'. If I remove that option from the YAML configuration in the UI, I can save. Doing this in the CLI doesn't raise any issues.

Now that I've added it to the profile via the CLI, if I navigate back to the YAML view I don't see it.

# Steps to reproduce

 1. Create a profile with two devices via the CLI. In my case it was a root disk and an ISO. I didn't use the UI way since I don't store my ISOs as a volume because downloading onto the host was faster than uploading my own copy, and that method duplicates disk space unnecessarily when you already have the ISO files.

Example:
```yaml
name: 22.04.5
description: Jammy Server ISO
config:
  limits.cpu: "2"
  limits.memory: 4GiB
devices:
  iso:
    source: /home/ubuntu/isos/ubuntu-22.04.5-live-server-amd64.iso
    type: disk
  root:
    path: /
    pool: default
    size: 25GiB
    type: disk
used_by: []
```
 2. Navigate to the profile you created in the UI and go to the YAML configuration
 3. Attempt to add the boot.priority to the two devices. In my case I added a priority of `10` to the root, and `5` to the ISO. This should trigger an error
 4. Remove those fields from the UI and attempt to save. Should work
 5. Via the CLI, edit the profile to add those parameters
 6. Go back to the UI and look at the YAML and they're not there.
