### ISSUE TITLE
Prevent use of another OVN network's volatile IP on different OVN network

### ISSUE THREAD

**Issue by tomponline** [canonical/lxd#14328]
It is possible for one OVN network to use an IP that is allocated to a different OVN network.

Reproducer:

Uplink network lxdbr0.
Note: 

- ipv4.ovn.ranges: 10.64.52.11-10.64.52.20
- ipv4.routes: 10.64.52.11/32 (this overlaps with ipv4.ovn.ranges).

```
 lxc network show lxdbr0
name: lxdbr0
description: ""
type: bridge
managed: true
status: Created
config:
  ipv4.address: 10.64.52.1/24
  ipv4.dhcp.ranges: 10.64.52.2-10.64.52.10
  ipv4.nat: "true"
  ipv4.ovn.ranges: 10.64.52.11-10.64.52.20
  ipv4.routes: 10.64.52.11/32
  ipv6.address: fd42:1b79:16a9:d15c::1/64
  ipv6.nat: "true"
```

```
lxc network create ovn1 --type=ovn network=lxdbr0
lxc network show ovn1
name: ovn1
description: ""
type: ovn
managed: true
status: Created
config:
  bridge.mtu: "1500"
  ipv4.address: 10.143.174.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:49ae:dd4d:97f3::1/64
  ipv6.nat: "true"
  network: lxdbr0
  volatile.network.ipv4.address: 10.64.52.11
  volatile.network.ipv6.address: fd42:1b79:16a9:d15c:216:3eff:fecc:717

lxc network create ovn2 --type=ovn network=lxdbr0
lxc network show ovn2
name: ovn2
description: ""
type: ovn
managed: true
status: Created
config:
  bridge.mtu: "1500"
  ipv4.address: 10.132.18.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:4aa5:48ce:c737::1/64
  ipv6.nat: "true"
  network: lxdbr0
  volatile.network.ipv4.address: 10.64.52.12
  volatile.network.ipv6.address: fd42:1b79:16a9:d15c:216:3eff:fe07:6e7e
```

Note: ovn1 network has `volatile.network.ipv4.address: 10.64.52.11` as its router IP on the uplink.
This is the same IP as is allocated in ipv4.routes to be used for IP passthrough `10.64.52.11/32`.

We should allow creation of a network forward ovn1 using `10.64.52.11` as the network already claims that IP via its `volatile.network.ipv4.address`.
```
lxc network forward create ovn1 10.64.52.11
Network forward 10.64.52.11 created
lxc network forward delete ovn1 10.64.52.11
```

However we shouldn't be able to create a network forward on ovn2 using the `10.64.52.11`  IP claimed by ovn1.

```
lxc network forward create ovn2 10.64.52.11
Network forward 10.64.52.11 created
```

Also shouldn't be allowed to use direct IP passthrough using the IP claimed by the OVN1 network:

```
lxc launch images:alpine/3.20 c1 -n ovn2 -d eth0,ipv4.routes.external=10.64.52.11/32
```
