### ISSUE TITLE
Feature Request: Multiple snapshot schedules

### ISSUE THREAD

**Issue by vosdev** [canonical/lxd#14427]
I would like to request the ability to make multiple snapshot schedules. 

For example I would like to keep 7 daily snapshots, 4 weekly snapshots and 6 monthly snapshots.

Currently `config.snapshots` is a map and only allows for a very limited amount of config, like so: 
```yaml
config:
  snapshots.expiry: 7d
  snapshots.pattern: snap-{{ creation_date|date:'2006-01-02_15-04-05' }}
  snapshots.schedule: '@daily'
```

The feature I would like to request is something like this:
```yaml
config:
  snapshots:
    - expiry: 7d
      pattern: daily-{{ creation_date|date:'2006-01-02_15-04-05' }}
      schedule: '@daily'
    - expiry: 4w
      pattern: weekly-{{ creation_date|date:'2006-01-02_15-04-05' }}
      schedule: '@weekly'
    - expiry: 6m
      pattern: monthly-{{ creation_date|date:'2006-01-02_15-04-05' }}
      schedule: '@monthly'
```

sidenote: I tried creating a topic on the ubuntu discourse to request this feature but the 'New topic' button doesn't exist for me. I'm a level 0 user joined on sept 29. The discourse seems pretty dead which makes sense if new users aren't able to create new topics.

**Comment by mionaalex** [comment]
@vosdev Ubuntu Discourse requires users to interact with the site for a bit before being allowed to post new topics. I've upped your trust level, so you should be able to post now.

As for your request, we will be working on improvements to snapshots and scheduling in the coming months, so we'll take this into account as we do so.

**Comment by vosdev** [comment]
@mionaalex That's great to hear. Is there also a feature planned to sync instances and all their snapshots to a remote location? 

Having snapshots on my local filesystem (Or my Ceph cluster) is great but in terms of actual backups I would like the ability to store them on a completely separate system.

Like VMWare/Hyper-V with Veeam :)

I can open a new issue if that's preferred

**Comment by mionaalex** [comment]
@vosdev This is exactly what we plan to do during this development cycle. No need for a new issue, this feature is already planned for, it will be available sometime next year :)

**Comment by vosdev** [comment]
Changing the individual snapshot schedules to a key/value instead of a list makes more sense, like so:

```yaml
  snapshots.daily.expiry: 7d
  snapshots.daily.pattern: daily-{{ creation_date|date:'2006-01-02_15-04-05' }}
  snapshots.daily.schedule: '@daily'
  snapshots.weekly.expiry: 4w
  snapshots.weekly.pattern: weekly-{{ creation_date|date:'2006-01-02_15-04-05' }}
  snapshots.weekly.schedule: '@weekly'
```

This also allows for merging through profiles. I could create a profile for monthly snapshots and it would easily merge with the other snapshot schedules.

```yaml
  snapshots.monthly.expiry: 12m
  snapshots.monthly.pattern: monthly-{{ creation_date|date:'2006-01-02_15-04-05' }}
  snapshots.monthly.schedule: '@monthly'
```
