### ISSUE TITLE
Containers do not start again when the host is not shut down properly

### ISSUE THREAD

**Issue by dbruno74** [canonical/lxd#14843]
LXD: latest/edge
OS: core24

After creating containers with the nvidia gpu device, and the host is not shut down properly [ i.e. it loses power ], the instances won't start again after the host is started, even withj the manual start command.

LXD returns as exception:

```
Failed to start device "nvidia-gpu": Failed to create device "/var/snap/lxd/common/lxd/devices/oel-ogrp623/cdi.unix.nvidia--gpu.dev-nvidia0" for "/dev/nvidia0": file exists
```

For clarity, devices config is:
```
devices:
  nvidia-gpu:
    gputype: physical
    id: [nvidia.com/gpu=all](http://nvidia.com/gpu=all)
    type: gpu
```

Note that checking the lxd devices dir, the following files are still present:
```
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.etc-vulkan-icd.d-nvidia_icd.json
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.etc-vulkan-implicit_layer.d-nvidia_layers.json
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-bin-nvidia--smi
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libEGL_nvidia.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libGLESv1_CM_nvidia.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libGLESv2_nvidia.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libGLX_nvidia.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libcuda.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libcudadebugger.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvcuvid.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--allocator.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--cfg.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--egl--gbm.so.1.1.1
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--egl--wayland.so.1.1.13
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--eglcore.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--encode.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--fbc.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--glcore.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--glsi.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--glvkspirv.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--gpucomp.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--ml.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--ngx.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--nvvm.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--opencl.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--opticalflow.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--pkcs11--openssl3.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--pkcs11.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--ptxjitcompiler.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--rtcore.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvidia--tls.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-libnvoptix.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-nvidia-xorg-libglxserver_nvidia.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 [cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-nvidia-xorg-nvidia_drv.so](http://cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-nvidia-xorg-nvidia_drv.so/)
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-lib-x86_64--linux--gnu-vdpau-libvdpau_nvidia.so.550.127.05
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-share-X11-xorg.conf.d-10--nvidia.conf
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-share-egl-egl_external_platform.d-10_nvidia_wayland.json
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-share-egl-egl_external_platform.d-15_nvidia_gbm.json
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-share-glvnd-egl_vendor.d-10_nvidia.json
-rw-r--r-- 1 root    root           0 Jan 22 17:43 cdi.disk.nvidia--gpu.usr-share-nvidia-nvoptix.bin
crw-rw---- 1 1065536 1065536 226,   1 Jan 22 17:43 cdi.unix.nvidia--gpu.dev-dri-card1
crw-rw---- 1 1065536 1065536 226, 128 Jan 22 17:43 cdi.unix.nvidia--gpu.dev-dri-renderD128
crw-rw-rw- 1 1065536 1065536 195, 254 Jan 22 17:43 cdi.unix.nvidia--gpu.dev-nvidia--modeset
crw-rw-rw- 1 1065536 1065536 510,   0 Jan 22 17:43 cdi.unix.nvidia--gpu.dev-nvidia--uvm
crw-rw-rw- 1 1065536 1065536 510,   1 Jan 22 17:43 cdi.unix.nvidia--gpu.dev-nvidia--uvm--tools
crw-rw-rw- 1 1065536 1065536 195,   0 Jan 22 17:43 cdi.unix.nvidia--gpu.dev-nvidia0
crw-rw-rw- 1 1065536 1065536 195, 255 Jan 22 17:43 cdi.unix.nvidia--gpu.dev-nvidiactl
-rw-r--r-- 1 root    root        9286 Jan 22 17:43 nvidia-gpu_cdi_config_devices.json
-rw-r--r-- 1 root    root         805 Jan 22 17:43 nvidia-gpu_cdi_hooks.json
```

Manually mounting to container volume and checking the filesystem, no files are present under /dev

The instance can be started again by purging the files under the device directly:

rm /var/snap/lxd/common/lxd/devices/oel-ogrp623/*

**Comment by jocado** [comment]
@tomponline and @dbruno74 

There seems to have been a regression which is allowing this to happen again, reproducible consistently on real hardware.  Should I create a new bug, or do you want to re-open this one ?

**Comment by tomponline** [comment]
Please can you post the new details here (which versions, repro steps etc)

**Comment by jocado** [comment]
Ubuntu Core 24.

Issue reproduced on the following lxd snap version/revisions:

```
6.4-2336111  34099 # old 6/stable
6.5-72c8a10  35210 # 6/stable
6.5-1edcf04  35598 # 6/candidate
```

Instance GPU config:

```
  nvidia-gpu:
    gputype: physical
    id: nvidia.com/gpu=all
    type: gpu
```


Repro steps are similar as previously:

- Physical system running multiple more container instances using nvidia GPU
- Non-graceful reboot of system [ in this case we are doing a "warm reset" from the iRMC ]
- The lxc containers are not started, and cannot be manually started - they remain state `STOPPED`


The main error is:
```
Failed to start device "nvidia-gpu": Failed to create device "/var/snap/lxd/common/lxd/devices/{instance-name}/cdi.unix.nvidia--gpu.dev-nvidia0" for "/dev/nvidia0": file exists
```

**Comment by tomponline** [comment]
@jocado please can we see the container config `lxc config show <instance> --expanded` as just tried to reproduce this locally no to avail.

**Comment by jocado** [comment]
@tomponline 

Please find the config below for one of the instances.  Some of the data had to be been removed or obfuscated, but I really doubt it's relevant, as it's cloud-init [ instance isn't even powering on ], and some custom instance config used which is kind of metadata for us.

```
architecture: x86_64
config:
  cloud-init.network-config: |
    ~~~8<~~~
  cloud-init.user-data: |
    ~~~8<~~~
  cloud-init.vendor-data: |
    ~~~8<~~~
  image.architecture: amd64
  image.description: Ubuntu 24.04 LTS ({name-of-model}_0.0.30) Edge Compute
    Platform (20250814)
  image.edge: "true"
  image.model: {name-of-model}
  image.os: ubuntu
  image.release: noble
  image.version: 0.0.30
  limits.kernel.nice: "-20"
  limits.kernel.rtprio: "99"
  nvidia.driver.capabilities: all
  security.idmap.isolated: "true"
  security.nesting: "true"
  security.syscalls.intercept.mknod: "true"
  security.syscalls.intercept.setxattr: "true"
  user._custom.instance.config: '{custom_data}'
  user._custom.some.thing: '{custom_data}'
  user.meta-data: |
    #cloud-config
    dsmode: local
    instance_id: orblxc
  volatile.base_image: e8a75c778b46faf6494b0ff49048bba777b88a6b7925ba13b3befebd6c90652d
  volatile.cloud-init.instance-id: bde3b7af-bcef-4549-9b37-9adc707124ec
  volatile.idmap.base: "1065536"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1065536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1065536,"Nsid":0,"Maprange":65536}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1065536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1065536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.public.host_name: macccd39451
  volatile.public.hwaddr: 00:16:3e:75:8a:c2
  volatile.public.last_state.created: "false"
  volatile.uuid: 35e94196-1428-44a1-8453-96f8e9ab638f
  volatile.uuid.generation: 35e94196-1428-44a1-8453-96f8e9ab638f
devices:
  nvidia-gpu:
    gputype: physical
    id: nvidia.com/gpu=all
    type: gpu
  public:
    name: net0
    nictype: macvlan
    parent: enp24s0f0
    type: nic
  root:
    path: /
    pool: edge-pool
    type: disk
ephemeral: false
profiles:
- edge-default
- edge-cloud-init
- edge-nvidia
- edge-osp-apt-config
stateful: false
description: {instance-name}
```

**Comment by tomponline** [comment]
> id: nvidia.com/gpu=all

This might be relevant. Are you passing through multiple GPUs via a single LXD device definition?

**Comment by tomponline** [comment]
If a single card is passed through using `nvidia.com/gpu=0` does the issue still occur?

**Comment by jocado** [comment]
@tomponline 

I just tried changing the config as follows, then restarting the instance. The instance restarted fine, but the when I tried the non-graceful host reboot the same issue occurred I'm afraid.

```
  nvidia-gpu:
    gputype: physical
    id: nvidia.com/gpu=0
    type: gpu
```
