### ISSUE TITLE
CLI does not shows instance volatile.eth0.last_state.ip_addresses

### ISSUE THREAD

**Issue by norbertoisaac** [canonical/lxd#15032]
Hi there

Info:
``` 
# cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

# snap info lxd
installed:          5.21.3-75def3c            (32455) 118MB held

# lxc config show C-Syslog
architecture: x86_64
config:
  image.architecture: x86_64
  image.description: Ubuntu 24.04 LTS minimal (20240608)
  image.os: ubuntu
  image.release: noble
  limits.memory: 8GB
  limits.processes: "500"
  volatile.base_image: b87775d887ac388a4a93c2508013b2b10e0a001d2b5c8dc6ca8a7b8bc1e1d2b1
  volatile.cloud-init.instance-id: d46d02ec-1827-427f-9d6f-9a3ae63b0420
  volatile.eth0.host_name: vethe899d39c
  volatile.eth0.hwaddr: 00:16:3e:58:0f:f4
  volatile.eth0.name: eth0
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: 25e5dda2-f6df-447e-835c-61a195efc64c
  volatile.uuid.generation: 25e5dda2-f6df-447e-835c-61a195efc64c
devices:
  eth0:
    network: Net10.143.7.10
    type: nic
  root:
    path: /
    pool: pool_local_btrfs
    size: 200GB
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

# lxc network show Net10.143.7.10
name: Net10.143.7.10
description: ""
type: ovn
managed: true
status: Created
config:
  bridge.mtu: "1442"
  ipv4.address: 192.168.0.1/24
  ipv4.nat: "true"
  ipv4.nat.address: 10.143.7.10
  ipv6.address: none
  network: UP496
  volatile.network.ipv4.address: 10.143.7.10
  volatile.network.ipv6.address: '::'
used_by:
- /1.0/instances/C-Syslog?project=IAAS-Logs
locations:
- h1
- h2
```

It does not shows volatile ipv4 address on lxc cli, on UI it shows correctly
