### ISSUE TITLE
lxc network list-allocations does not prints macvlan interfaces

### ISSUE THREAD

**Issue by norbertoisaac** [canonical/lxd#15180]
Hi there
For some reason `lxc network list-allocations` command does not shows interfaces belong MACVLAN networks, for example:
```
# lxc network list-allocations --all-projects
+---------+---------+---------+------+-----+------------------+
| USED BY | ADDRESS | NETWORK | TYPE | NAT | HARDWARE ADDRESS |
+---------+---------+---------+------+-----+------------------+

# lxc config show C-SyslogDist-h1
architecture: x86_64
config:
  cloud-init.network-config: |
    version: 2
    ethernets:
        eth3:
            dhcp4: false
            dhcp6: false
            addresses:
              - 169.254.3.3/24
  image.architecture: x86_64
  image.description: Ubuntu 24.04 LTS minimal (20240608)
  image.os: ubuntu
  image.release: noble
  limits.cpu: "4"
  limits.memory: 8GB
  limits.processes: "500"
  volatile.base_image: b87775d887ac388a4a93c2508013b2b10e0a001d2b5c8dc6ca8a7b8bc1e1d2b1
  volatile.cloud-init.instance-id: 14e0e74b-400b-4d9a-aa15-0ad7b804f8b7
  volatile.eth3.host_name: mac3b24635d
  volatile.eth3.hwaddr: 00:16:3e:e2:31:47
  volatile.eth3.last_state.created: "true"
  volatile.idmap.base: "0"
  volatile.idmap.current: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":1000000000},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":1000000000}]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: "false"
  volatile.uuid: d6b3813a-c5c4-437d-b9c9-2a4958ca3a26
  volatile.uuid.generation: d6b3813a-c5c4-437d-b9c9-2a4958ca3a26
devices:
  eth3:
    name: eth3
    network: NetMV3
    type: nic
  root:
    path: /
    pool: st_local_btrfs
    size: 10GB
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""

root@C-SyslogDist-h1:~# ip -4 -br addr
lo               UNKNOWN        127.0.0.1/8 
eth3@if122       UP             169.254.3.3/24 
root@C-SyslogDist-h1:~# ip -br link
lo               UNKNOWN        00:00:00:00:00:00 <LOOPBACK,UP,LOWER_UP> 
eth3@if122       UP             00:16:3e:e2:31:47 <BROADCAST,MULTICAST,UP,LOWER_UP>

# lxc network show NetMV3
name: NetMV3
description: ""
type: macvlan
managed: true
status: Created
config:
  vlan: "3"
used_by:
- /1.0/instances/C-SyslogDist-h1?project=IAAS-Logs
- /1.0/instances/C-SyslogDist-h2?project=IAAS-Logs
- /1.0/instances/C1
locations:
- h1
- h2
```

System info:
```
# snap info lxd
name:      lxd
summary:   LXD - container and VM manager
publisher: Canonical✓
store-url: https://snapcraft.io/lxd
contact:   lxd@lists.canonical.com
license:   AGPL-3.0
...
installed:          5.21.3-75def3c            (32455) 118MB held

# cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```
