### ISSUE TITLE
Metrics endpoint reporting humongus value for free memory on frozen VM

### ISSUE THREAD

**Issue by edlerd** [canonical/lxd#15643]
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

ubuntu

### Distribution version

snap

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
Name    Version         Rev    Tracking       Publisher   Notes
core20  20250213        2501   latest/stable  canonical✓  base,disabled
core20  20250407        2571   latest/stable  canonical✓  base
core22  20250315        1908   latest/stable  canonical✓  base,disabled
core22  20250408        1963   latest/stable  canonical✓  base
core24  20250318        888    latest/stable  canonical✓  base,disabled
core24  20250504        988    latest/stable  canonical✓  base
lxd     5.21.3-c5ae129  33110  5.21/stable    canonical✓  -
snapd   2.67.1          23771  latest/stable  canonical✓  snapd,disabled
snapd   2.68.4          24505  latest/stable  canonical✓  snapd
```

### Output of "lxc info" or system info if it fails

```shell
-
```

### Issue description

The `GET /1.0/metrics` endpoint sometimes reports wrong values for memory. See the example below, where free and available memory is way bigger and unreasonably high when compared to total memory.

```
lxd_memory_MemAvailable_bytes{name="nms",project="default",state="RUNNING",type="virtual-machine"} 1.844674407367206e+19
lxd_memory_MemFree_bytes{name="nms",project="default",state="RUNNING",type="virtual-machine"} 1.844674407367206e+19
lxd_memory_MemTotal_bytes{name="nms",project="default",state="RUNNING",type="virtual-machine"} 1.073741824e+09
```

Full instance configuration is 

```
name: nms
description: ''
status: Frozen
status_code: 110
created_at: '2025-05-22T07:20:35.086464209Z'
last_used_at: '2025-05-23T09:06:39.579476605Z'
location: lxd0
type: virtual-machine
project: default
architecture: x86_64
ephemeral: false
stateful: false
profiles:
  - default
config:
  image.architecture: amd64
  image.description: ubuntu 24.04 LTS amd64 (release) (20250516)
  image.label: release
  image.os: ubuntu
  image.release: noble
  image.serial: '20250516'
  image.type: disk1.img
  image.version: '24.04'
  volatile.base_image: 114a1bc50c4d10b31da8c9fc91c181713acf0ce37eee13521dcfa3325e02ab84
  volatile.cloud-init.instance-id: a3feb58a-239d-4142-9ba1-d818bd7bc2c8
  volatile.eth-1.host_name: tap198af091
  volatile.eth-1.hwaddr: 00:16:3e:99:12:2e
  volatile.last_state.power: RUNNING
  volatile.last_state.ready: 'false'
  volatile.uuid: a36842fb-d08b-4cdb-b056-1e5852fde1fd
  volatile.uuid.generation: a36842fb-d08b-4cdb-b056-1e5852fde1fd
  volatile.vsock_id: '2720916272'
devices: {}
```

### Steps to reproduce

Sadly, I have no reproducer.

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)
