### ISSUE TITLE
Allow setting the macvlan mode (bridge, vepa, passthru or private) on macvlan interfaces

### ISSUE THREAD

**Issue by pieterverberne** [canonical/lxd#15667]
For network testing application we have an somewhat unusal network setup. It happens to be the case that we need to have a macvlan interface in vepa mode.

The problem would be solved if we could set the macvlan mode as such:
```
devices:
  eth1:
    name: eth1
    nictype: macvlan
    parent: enx6805ca1f3d00
    type: nic
    mode: vepa
```

Could the mode option be added to the macvlan device configuration?

See also:

[Ubuntu Discourse question](https://discourse.ubuntu.com/t/set-macvlan-mode-bridge-vepa-passthru-or-private/61540)
