### ISSUE TITLE
`lxc network forward create --allocate` can allocate the physical network's `ipv4.gateway`

### ISSUE THREAD

**Issue by MggMuggins** [canonical/lxd#15857]
### Please confirm

- [x] I have searched existing issues to check if an issue already exists for the bug I encountered.

### Distribution

Ubuntu

### Distribution version

24.04

### Output of "snap list --all lxd core20 core22 core24 snapd"

```shell
$ snap list --all lxd core20 core22 core24 snapd
Name    Version         Rev    Tracking        Publisher   Notes
core20  20250429        2582   latest/stable   canonical✓  base,disabled
core20  20250526        2599   latest/stable   canonical✓  base
core22  20250425        1981   latest/stable   canonical✓  base,disabled
core22  20250528        2010   latest/stable   canonical✓  base
core24  20250504        988    latest/stable   canonical✓  base,disabled
core24  20250526        1006   latest/stable   canonical✓  base
lxd     5.21.3-c5ae129  33110  5.21/candidate  canonical✓  disabled,in-cohort
lxd     5.21.3-27d70fa  34068  5.21/candidate  canonical✓  in-cohort
snapd   2.68.4          24505  latest/stable   canonical✓  snapd,disabled
snapd   2.68.5          24718  latest/stable   canonical✓  snapd
```

### Output of "lxc info" or system info if it fails

```shell
$ snap list --all microovn microceph microcloud
Name        Version                 Rev   Tracking      Publisher   Notes
microceph   19.2.0+snapd37ac0ff9d   1344  squid/stable  canonical✓  disabled
microceph   19.2.0+snap3b53da1c21   1355  squid/stable  canonical✓  -
microcloud  2.1.0-3e8b183           1144  2/stable      canonical✓  -
microovn    24.03.2+snapa2c59c105b  667   24.03/stable  canonical✓  -
$ uname -a
Linux houston 6.8.0-60-generic #63-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 15 19:04:15 UTC 2025 x86_64 x86_64 x86_64 GNU/Linux
```

### Issue description

For this UPLINK configuration:
```yaml
name: UPLINK
description: ""
type: physical
managed: true
status: Created
config:
  dns.nameservers: 10.0.0.1,8.8.8.8
  ipv4.gateway: 10.0.0.1/24
  ipv4.ovn.ranges: 10.0.0.20-10.0.0.80
  ipv4.routes: 10.0.0.0/28
  volatile.last_state.created: "false"
```

And an OVN network `maas0`:
```yaml
name: maas0
description: ""
type: ovn
managed: true
status: Created
config:
  bridge.mtu: "1442"
  ipv4.address: 10.82.24.1/24
  ipv4.nat: "true"
  ipv6.address: fd42:4a34:d720:fd7b::1/64
  ipv6.nat: "true"
  network: UPLINK
  volatile.network.ipv4.address: 10.0.0.23
```

Creating a network forward with `--allocate` can allocate the UPLINK's `ipv4.gateway`:
```
$ lxc network forward create maas0 --allocate ipv4 target_address=10.82.24.5
Network forward 10.0.0.1 created
```

I'm no networking expert so this setup might be a little bit insane, but I figure it's probably best to prevent LXD using addresses that it knows are in use.

### Steps to reproduce

Create an UPLINK network with
```yaml
config:
  ipv4.gateway=10.0.0.1/24
  ipv4.routes=10.0.0.0/30
```

and create a few routes; I haven't tested this but I expect it reproduces trivially.

### Information to attach

- [ ] Any relevant kernel output (`dmesg`)
- [ ] Instance log (`lxc info NAME --show-log`)
- [ ] Instance configuration (`lxc config show NAME --expanded`)
- [ ] Main daemon log (at `/var/log/lxd/lxd.log` or `/var/snap/lxd/common/lxd/logs/lxd.log`)
- [ ] Output of the client with `--debug`
- [ ] Output of the daemon with `--debug` (or use `lxc monitor` while reproducing the issue)
