### ISSUE TITLE
While recovering corrupted host FS, data is recovered but LXC containers won't stay started

### ISSUE THREAD

**Issue by curvedinf** [canonical/lxd#5275]
# Required information

 * Distribution: Ubuntu
 * Distribution version: 18.04
 * lxc info:
``` config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- candid_authentication
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 162.232.249.191:8443
  - '[2600:1702:4110:7e00::69e]:8443'
  - '[2600:1702:4110:7e00:1182:5a43:5565:f9f2]:8443'
  - '[2600:1702:4110:7e00:591c:5ce4:6488:e79d]:8443'
  - 10.189.200.1:8443
  - '[fd42:8ae:5f3d:f6cf::1]:8443'
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIIFfzCCA2egAwIBAgIRANKFudZHePTxaz6EyduD8NQwDQYJKoZIhvcNAQELBQAw
    NjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEBQ
    dW5pc2hlcjAeFw0xODA5MjYyMjQ4MjhaFw0yODA5MjMyMjQ4MjhaMDYxHDAaBgNV
    BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxFjAUBgNVBAMMDXJvb3RAUHVuaXNoZXIw
    ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCsNAOQ4zYi720W3U9VZaIg
    sJDwMFWHXVDr/2hO3LItvkA9IxIIS64/ljO1kz3VT59FES3o5c04thTo9p9KTUVV
    RxFC7JEE5fAsi0f8Lmo1mSlV1BVcd/3dwSi/wIhufj3OS1MS0tUrj38AUoPRm4TB
    HAOovRWk2xoOZky9f15Md6+5er9IsWXHFXTxe/wj3PH22zjGVLoeyyW6Q5hlF7W9
    eHZY1Af8jHKQC6XS6rkJCmSxFHJLIW5tCzZPaIb6CiroUt9peuLo1dqtI+Y+LB53
    DaXy600MsSNSMtmi1+jl5GAlZA/VlfA3MVyO6NIhni5mmv6H/pMha9l8B4esZloL
    gVVL4/ZXxOdMbw2opt/FVKuFJwmoKRuWSKj+25aCDCy5mbIwrk4Uu0+HIOXGaGum
    hZi3s6iwWjfU7T9AGHg7CHnP6LNnecn+Gsd7g2C06MAAZUJx6j+umYMyMibsOPK8
    r7kdjIWA0UdzoRI3vO9UCbkdZHgUcTOBkXs0jkNzPFqrilynqhJ8P82uKC8dOP36
    +SQgO27+nNFRQC9rwbS8bgabwB9VnrcxKZ/IvkGYfiuIJEngRYuwOZ0U1+0DldMX
    7qOCze3ZIlIMkkiVPNFzUziLCNTSZe61MGNBmeXdCv75qg1qvchysadwNXJQn+3A
    vp3qC2Z6+f9AqaGrTccwcQIDAQABo4GHMIGEMA4GA1UdDwEB/wQEAwIFoDATBgNV
    HSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAME8GA1UdEQRIMEaCCFB1bmlz
    aGVyhwSi6Pm/hxAmABcCQRB+AAAAAAAAAAZ9hxAmABcCQRB+AHBd5yfDEUoZhxAm
    ABcCQRB+AHyK8ooVab/HMA0GCSqGSIb3DQEBCwUAA4ICAQAqnUNoqWoPgxY1jdCe
    srJ2jd4iD0N2lJU6w2qlcK2UYfhR2ONcxKhV4K8E0kreGsmibAE6ywCq7S1X1A+5
    KfSbpLe6t6eW7hvYTQ5Wu1dJxXIJ+lBO7ljNwKIes30mi06cRWj5xUM/UI2UbSpG
    5ORsef7US2dClBL4SDe72CpomvldHNd0EsP3JHdzv9PSzGAIsgE627jnDuewSrSN
    koqPMKjlo5YNDtMl40vJfgKjBSJCSt/0CPTxe34zrJ697aEqcoZnlKeMBgZwz3AM
    wQb1KN+wysMWxEVgZkLQP3f0ox1ahCbD+jQPUaWvu/WFoTWcgw0jOnDTDF0Fi53L
    eazWvdvdbH0HeWRqq7f+/o6rUZKj8YhTKuP1Bqm+BICYnZgwe0rui2AIsQTIyC9F
    714uwW+BuQ8ZNwrGLqCXp3OXGi5HwIxEJl2/YMPB8zjzrW8KdtVbPlOH6RiHMLKj
    Ri9xOElWthtgIDCsKS8oxfTJlBIHd/Nt/WbuzzRvVQ0xYc0XhSQX7hi4xjlBhr4E
    1e/iwUD+zbZGk+QM061TIerf0E1/ChGSndjzVnZvU099M03uGIs5TFk6fzmTXYFN
    4RMYtfPFt2MOUohEn67LwI+9CWO6kW6akgmBmFejYELxgQyVmS2iPviY35aNFbtY
    61vlWToGe+pKQoAt6kv/yUdwCA==
    -----END CERTIFICATE-----
  certificate_fingerprint: d32fa9ec280c3bdf630ad122a9d94058804b491b88068a79cd75a0b4e0cdb9e4
  driver: lxc
  driver_version: 3.0.2
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.15.0-38-generic
  server: lxd
  server_pid: 15020
  server_version: 3.0.2
  storage: dir
  storage_version: "1"
  server_clustered: false
  server_name: Punisher
```

# Issue description

My storage pool was running on a bcache filesystem who's backing devices became corrupted. I was able to recover most of the data and transfer to a new filesystem. I was also able to successfully migrate the containers' metadata to a new LXD pool wherein almost all LXC commands work successfully. However starting containers seems to complete successfully and then immediately issue a stop.

Launching a new image creates start-able containers, so my issues is related to files recovered from the corrupt data. All containers from the corrupt FS have the same issue, but there is very little debugging information available using the standard methods. Any additional debug info could help find the issue.

# Steps to reproduce

 1. Have some containers on a working LXC
 2. Have a corrupt FS and run fsck on it
 3. Hook up a new LXD instance to the existing recovered storage pool data
4. Start the containers

# Information to attach

* lxc start NODE --debug
```
DBUG[11-12|23:15:53] Connecting to a local LXD over a Unix socket 
DBUG[11-12|23:15:53] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0
DBUG[11-12|23:15:53] Got response struct from LXD 
DBUG[11-12|23:15:53] 
	{
		"config": {
			"core.https_address": "[::]:8443",
			"core.trust_password": true
		},
		"api_extensions": [
			"storage_zfs_remove_snapshots",
			"container_host_shutdown_timeout",
			"container_stop_priority",
			"container_syscall_filtering",
			"auth_pki",
			"container_last_used_at",
			"etag",
			"patch",
			"usb_devices",
			"https_allowed_credentials",
			"image_compression_algorithm",
			"directory_manipulation",
			"container_cpu_time",
			"storage_zfs_use_refquota",
			"storage_lvm_mount_options",
			"network",
			"profile_usedby",
			"container_push",
			"container_exec_recording",
			"certificate_update",
			"container_exec_signal_handling",
			"gpu_devices",
			"container_image_properties",
			"migration_progress",
			"id_map",
			"network_firewall_filtering",
			"network_routes",
			"storage",
			"file_delete",
			"file_append",
			"network_dhcp_expiry",
			"storage_lvm_vg_rename",
			"storage_lvm_thinpool_rename",
			"network_vlan",
			"image_create_aliases",
			"container_stateless_copy",
			"container_only_migration",
			"storage_zfs_clone_copy",
			"unix_device_rename",
			"storage_lvm_use_thinpool",
			"storage_rsync_bwlimit",
			"network_vxlan_interface",
			"storage_btrfs_mount_options",
			"entity_description",
			"image_force_refresh",
			"storage_lvm_lv_resizing",
			"id_map_base",
			"file_symlinks",
			"container_push_target",
			"network_vlan_physical",
			"storage_images_delete",
			"container_edit_metadata",
			"container_snapshot_stateful_migration",
			"storage_driver_ceph",
			"storage_ceph_user_name",
			"resource_limits",
			"storage_volatile_initial_source",
			"storage_ceph_force_osd_reuse",
			"storage_block_filesystem_btrfs",
			"resources",
			"kernel_limits",
			"storage_api_volume_rename",
			"macaroon_authentication",
			"network_sriov",
			"console",
			"restrict_devlxd",
			"migration_pre_copy",
			"infiniband",
			"maas_network",
			"devlxd_events",
			"proxy",
			"network_dhcp_gateway",
			"file_get_symlink",
			"network_leases",
			"unix_device_hotplug",
			"storage_api_local_volume_handling",
			"operation_description",
			"clustering",
			"event_lifecycle",
			"storage_api_remote_volume_handling",
			"nvidia_runtime",
			"candid_authentication"
		],
		"api_status": "stable",
		"api_version": "1.0",
		"auth": "trusted",
		"public": false,
		"auth_methods": [
			"tls"
		],
		"environment": {
			"addresses": [
				"162.232.249.191:8443",
				"[2600:1702:4110:7e00::69e]:8443",
				"[2600:1702:4110:7e00:1182:5a43:5565:f9f2]:8443",
				"[2600:1702:4110:7e00:591c:5ce4:6488:e79d]:8443",
				"10.189.200.1:8443",
				"[fd42:8ae:5f3d:f6cf::1]:8443"
			],
			"architectures": [
				"x86_64",
				"i686"
			],
			"certificate": "-----BEGIN CERTIFICATE-----\nMIIFfzCCA2egAwIBAgIRANKFudZHePTxaz6EyduD8NQwDQYJKoZIhvcNAQELBQAw\nNjEcMBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEWMBQGA1UEAwwNcm9vdEBQ\ndW5pc2hlcjAeFw0xODA5MjYyMjQ4MjhaFw0yODA5MjMyMjQ4MjhaMDYxHDAaBgNV\nBAoTE2xpbnV4Y29udGFpbmVycy5vcmcxFjAUBgNVBAMMDXJvb3RAUHVuaXNoZXIw\nggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCsNAOQ4zYi720W3U9VZaIg\nsJDwMFWHXVDr/2hO3LItvkA9IxIIS64/ljO1kz3VT59FES3o5c04thTo9p9KTUVV\nRxFC7JEE5fAsi0f8Lmo1mSlV1BVcd/3dwSi/wIhufj3OS1MS0tUrj38AUoPRm4TB\nHAOovRWk2xoOZky9f15Md6+5er9IsWXHFXTxe/wj3PH22zjGVLoeyyW6Q5hlF7W9\neHZY1Af8jHKQC6XS6rkJCmSxFHJLIW5tCzZPaIb6CiroUt9peuLo1dqtI+Y+LB53\nDaXy600MsSNSMtmi1+jl5GAlZA/VlfA3MVyO6NIhni5mmv6H/pMha9l8B4esZloL\ngVVL4/ZXxOdMbw2opt/FVKuFJwmoKRuWSKj+25aCDCy5mbIwrk4Uu0+HIOXGaGum\nhZi3s6iwWjfU7T9AGHg7CHnP6LNnecn+Gsd7g2C06MAAZUJx6j+umYMyMibsOPK8\nr7kdjIWA0UdzoRI3vO9UCbkdZHgUcTOBkXs0jkNzPFqrilynqhJ8P82uKC8dOP36\n+SQgO27+nNFRQC9rwbS8bgabwB9VnrcxKZ/IvkGYfiuIJEngRYuwOZ0U1+0DldMX\n7qOCze3ZIlIMkkiVPNFzUziLCNTSZe61MGNBmeXdCv75qg1qvchysadwNXJQn+3A\nvp3qC2Z6+f9AqaGrTccwcQIDAQABo4GHMIGEMA4GA1UdDwEB/wQEAwIFoDATBgNV\nHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAME8GA1UdEQRIMEaCCFB1bmlz\naGVyhwSi6Pm/hxAmABcCQRB+AAAAAAAAAAZ9hxAmABcCQRB+AHBd5yfDEUoZhxAm\nABcCQRB+AHyK8ooVab/HMA0GCSqGSIb3DQEBCwUAA4ICAQAqnUNoqWoPgxY1jdCe\nsrJ2jd4iD0N2lJU6w2qlcK2UYfhR2ONcxKhV4K8E0kreGsmibAE6ywCq7S1X1A+5\nKfSbpLe6t6eW7hvYTQ5Wu1dJxXIJ+lBO7ljNwKIes30mi06cRWj5xUM/UI2UbSpG\n5ORsef7US2dClBL4SDe72CpomvldHNd0EsP3JHdzv9PSzGAIsgE627jnDuewSrSN\nkoqPMKjlo5YNDtMl40vJfgKjBSJCSt/0CPTxe34zrJ697aEqcoZnlKeMBgZwz3AM\nwQb1KN+wysMWxEVgZkLQP3f0ox1ahCbD+jQPUaWvu/WFoTWcgw0jOnDTDF0Fi53L\neazWvdvdbH0HeWRqq7f+/o6rUZKj8YhTKuP1Bqm+BICYnZgwe0rui2AIsQTIyC9F\n714uwW+BuQ8ZNwrGLqCXp3OXGi5HwIxEJl2/YMPB8zjzrW8KdtVbPlOH6RiHMLKj\nRi9xOElWthtgIDCsKS8oxfTJlBIHd/Nt/WbuzzRvVQ0xYc0XhSQX7hi4xjlBhr4E\n1e/iwUD+zbZGk+QM061TIerf0E1/ChGSndjzVnZvU099M03uGIs5TFk6fzmTXYFN\n4RMYtfPFt2MOUohEn67LwI+9CWO6kW6akgmBmFejYELxgQyVmS2iPviY35aNFbtY\n61vlWToGe+pKQoAt6kv/yUdwCA==\n-----END CERTIFICATE-----\n",
			"certificate_fingerprint": "d32fa9ec280c3bdf630ad122a9d94058804b491b88068a79cd75a0b4e0cdb9e4",
			"driver": "lxc",
			"driver_version": "3.0.2",
			"kernel": "Linux",
			"kernel_architecture": "x86_64",
			"kernel_version": "4.15.0-38-generic",
			"server": "lxd",
			"server_pid": 15020,
			"server_version": "3.0.2",
			"storage": "dir",
			"storage_version": "1",
			"server_clustered": false,
			"server_name": "Punisher"
		}
	} 
DBUG[11-12|23:15:53] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/containers/node-vtc
DBUG[11-12|23:15:53] Got response struct from LXD 
DBUG[11-12|23:15:53] 
	{
		"architecture": "x86_64",
		"config": {
			"limits.memory": "256MB",
			"raw.lxc": "lxc.net.0.ipv4.address = 10.189.200.50/24",
			"volatile.base_image": "4c0d4ca7196f8c74a21518d727452324db245414348618a7eadd140e9ff9a760",
			"volatile.eth0.hwaddr": "00:16:3e:05:8e:ca",
			"volatile.idmap.base": "0",
			"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]",
			"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]",
			"volatile.last_state.power": "STOPPED"
		},
		"devices": {
			"eth0": {
				"ipv4.address": "10.189.200.50",
				"name": "eth0",
				"nictype": "bridged",
				"parent": "lxdbr0",
				"type": "nic"
			}
		},
		"ephemeral": false,
		"profiles": [
			"default"
		],
		"stateful": false,
		"description": "",
		"created_at": "2018-09-27T11:29:03-04:00",
		"expanded_config": {
			"limits.memory": "256MB",
			"raw.lxc": "lxc.net.0.ipv4.address = 10.189.200.50/24",
			"volatile.base_image": "4c0d4ca7196f8c74a21518d727452324db245414348618a7eadd140e9ff9a760",
			"volatile.eth0.hwaddr": "00:16:3e:05:8e:ca",
			"volatile.idmap.base": "0",
			"volatile.idmap.next": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]",
			"volatile.last_state.idmap": "[{\"Isuid\":true,\"Isgid\":false,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536},{\"Isuid\":false,\"Isgid\":true,\"Hostid\":165536,\"Nsid\":0,\"Maprange\":65536}]",
			"volatile.last_state.power": "STOPPED"
		},
		"expanded_devices": {
			"eth0": {
				"ipv4.address": "10.189.200.50",
				"name": "eth0",
				"nictype": "bridged",
				"parent": "lxdbr0",
				"type": "nic"
			},
			"root": {
				"path": "/",
				"pool": "md0",
				"type": "disk"
			}
		},
		"name": "node-vtc",
		"status": "Stopped",
		"status_code": 102,
		"last_used_at": "2018-11-12T23:15:49.847696412-05:00",
		"location": ""
	} 
DBUG[11-12|23:15:53] Connected to the websocket 
DBUG[11-12|23:15:53] Sending request to LXD                   etag= method=PUT url=http://unix.socket/1.0/containers/node-vtc/state
DBUG[11-12|23:15:53] 
	{
		"action": "start",
		"timeout": 0,
		"force": false,
		"stateful": false
	} 
DBUG[11-12|23:15:53] Got operation from LXD 
DBUG[11-12|23:15:53] 
	{
		"id": "e9db1645-ef65-476b-a2f8-51a8032c1394",
		"class": "task",
		"description": "Starting container",
		"created_at": "2018-11-12T23:15:53.295802602-05:00",
		"updated_at": "2018-11-12T23:15:53.295802602-05:00",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/node-vtc"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": ""
	} 
DBUG[11-12|23:15:53] Sending request to LXD                   etag= method=GET url=http://unix.socket/1.0/operations/e9db1645-ef65-476b-a2f8-51a8032c1394
DBUG[11-12|23:15:53] Got response struct from LXD 
DBUG[11-12|23:15:53] 
	{
		"id": "e9db1645-ef65-476b-a2f8-51a8032c1394",
		"class": "task",
		"description": "Starting container",
		"created_at": "2018-11-12T23:15:53.295802602-05:00",
		"updated_at": "2018-11-12T23:15:53.295802602-05:00",
		"status": "Running",
		"status_code": 103,
		"resources": {
			"containers": [
				"/1.0/containers/node-vtc"
			]
		},
		"metadata": null,
		"may_cancel": false,
		"err": ""
	} 
```

*  lxc monitor of lxc start:
```
metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2018-11-12T23:14:43.268363606-05:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/containers/node-vtc
  level: dbug
  message: handling
timestamp: "2018-11-12T23:14:43.271722567-05:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/events
  level: dbug
  message: handling
timestamp: "2018-11-12T23:14:43.275667683-05:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New event listener: be600b10-77a4-450b-80b8-7b3ea6e2b431'
timestamp: "2018-11-12T23:14:43.275779582-05:00"
type: logging


metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/containers/node-vtc/state
  level: dbug
  message: handling
timestamp: "2018-11-12T23:14:43.276794386-05:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'New task operation: 2c582ce0-e8a9-4605-b153-2841c38dc0d5'
timestamp: "2018-11-12T23:14:43.305197556-05:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Started task operation: 2c582ce0-e8a9-4605-b153-2841c38dc0d5'
timestamp: "2018-11-12T23:14:43.305323862-05:00"
type: logging


metadata:
  class: task
  created_at: "2018-11-12T23:14:43.278962354-05:00"
  description: Starting container
  err: ""
  id: 2c582ce0-e8a9-4605-b153-2841c38dc0d5
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/node-vtc
  status: Running
  status_code: 103
  updated_at: "2018-11-12T23:14:43.278962354-05:00"
timestamp: "2018-11-12T23:14:43.305357515-05:00"
type: operation


metadata:
  class: task
  created_at: "2018-11-12T23:14:43.278962354-05:00"
  description: Starting container
  err: ""
  id: 2c582ce0-e8a9-4605-b153-2841c38dc0d5
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/node-vtc
  status: Pending
  status_code: 105
  updated_at: "2018-11-12T23:14:43.278962354-05:00"
timestamp: "2018-11-12T23:14:43.305256907-05:00"
type: operation


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0/operations/2c582ce0-e8a9-4605-b153-2841c38dc0d5
  level: dbug
  message: handling
timestamp: "2018-11-12T23:14:43.307471331-05:00"
type: logging


metadata:
  action: container-updated
  source: /1.0/containers/node-vtc
timestamp: "2018-11-12T23:14:43.540521276-05:00"
type: lifecycle


metadata:
  context: {}
  level: dbug
  message: Mounting DIR storage pool "md0"
timestamp: "2018-11-12T23:14:43.544156714-05:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting DIR storage pool "md0"
timestamp: "2018-11-12T23:14:43.550681997-05:00"
type: logging


metadata:
  context:
    action: start
    created: 2018-09-27 11:29:03 -0400 EDT
    ephemeral: "false"
    name: node-vtc
    stateful: "false"
    used: 2018-11-12 22:55:57.38841752 -0500 EST
  level: info
  message: Starting container
timestamp: "2018-11-12T23:14:43.551250007-05:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2018-11-12T23:14:43.575415906-05:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/26/onstart
  level: dbug
  message: handling
timestamp: "2018-11-12T23:14:43.579174413-05:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: Mounting DIR storage pool "md0"
timestamp: "2018-11-12T23:14:43.583122494-05:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: container node-vtc started: re-balancing'
timestamp: "2018-11-12T23:14:43.589348509-05:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Success for task operation: 2c582ce0-e8a9-4605-b153-2841c38dc0d5'
timestamp: "2018-11-12T23:14:43.834514755-05:00"
type: logging


metadata:
  context:
    action: start
    created: 2018-09-27 11:29:03 -0400 EDT
    ephemeral: "false"
    name: node-vtc
    stateful: "false"
    used: 2018-11-12 22:55:57.38841752 -0500 EST
  level: info
  message: Started container
timestamp: "2018-11-12T23:14:43.834404239-05:00"
type: logging


metadata:
  action: container-started
  source: /1.0/containers/node-vtc
timestamp: "2018-11-12T23:14:43.834477075-05:00"
type: lifecycle


metadata:
  class: task
  created_at: "2018-11-12T23:14:43.278962354-05:00"
  description: Starting container
  err: ""
  id: 2c582ce0-e8a9-4605-b153-2841c38dc0d5
  may_cancel: false
  metadata: null
  resources:
    containers:
    - /1.0/containers/node-vtc
  status: Success
  status_code: 200
  updated_at: "2018-11-12T23:14:43.278962354-05:00"
timestamp: "2018-11-12T23:14:43.834563396-05:00"
type: operation


metadata:
  context: {}
  level: dbug
  message: 'Disconnected event listener: be600b10-77a4-450b-80b8-7b3ea6e2b431'
timestamp: "2018-11-12T23:14:44.430654243-05:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /1.0
  level: dbug
  message: handling
timestamp: "2018-11-12T23:14:44.430506487-05:00"
type: logging


metadata:
  context:
    ip: '@'
    method: GET
    url: /internal/containers/26/onstop?target=stop
  level: dbug
  message: handling
timestamp: "2018-11-12T23:14:44.434612273-05:00"
type: logging


metadata:
  context:
    action: stop
    created: 2018-09-27 11:29:03 -0400 EDT
    ephemeral: "false"
    name: node-vtc
    stateful: "false"
    used: 2018-11-12 23:14:43.548697381 -0500 EST
  level: info
  message: Container initiated stop
timestamp: "2018-11-12T23:14:44.438197427-05:00"
type: logging


metadata:
  context: {}
  level: dbug
  message: 'Scheduler: container node-vtc stopped: re-balancing'
timestamp: "2018-11-12T23:14:44.534500519-05:00"
type: logging
```

* lxc info NAME --show-log
```
Name: node-vtc
Remote: unix://
Architecture: x86_64
Created: 2018/09/27 15:29 UTC
Status: Stopped
Type: persistent
Profiles: default

Log:

lxc node-vtc 20181113041554.225 WARN     conf - conf.c:lxc_setup_devpts:1620 - Invalid argument - Failed to unmount old devpts instance
```

* lxc config show NAME --expanded
```
architecture: x86_64
config:
  limits.memory: 256MB
  raw.lxc: lxc.net.0.ipv4.address = 10.189.200.50/24
  volatile.base_image: 4c0d4ca7196f8c74a21518d727452324db245414348618a7eadd140e9ff9a760
  volatile.eth0.hwaddr: 00:16:3e:05:8e:ca
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[{"Isuid":true,"Isgid":false,"Hostid":165536,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":165536,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.power: STOPPED
devices:
  eth0:
    ipv4.address: 10.189.200.50
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  root:
    path: /
    pool: md0
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```

* /var/log/lxd/lxd.log
```
action=start created=2018-09-27T11:29:03-0400 ephemeral=false lvl=info msg="Started container" name=node-vtc stateful=false t=2018-11-12T23:15:54-0500 used=2018-11-12T2$
action=stop created=2018-09-27T11:29:03-0400 ephemeral=false lvl=info msg="Container initiated stop" name=node-vtc stateful=false t=2018-11-12T23:15:54-0500 used=2018-1$
```

* /var/log/lxd/NAME/lxc.log
```
lxc node-vtc 20181113041554.225 WARN     conf - conf.c:lxc_setup_devpts:1620 - Invalid argument - Failed to unmount old devpts instance
```
* /var/log/lxd/NAME/console.log
```
/sbin/init: 9: /sbin/init: Syntax error: newline unexpected
```
