### ISSUE TITLE
Can't enable br_netfilter module in a containe

### ISSUE THREAD

**Issue by wusikijeronii** [canonical/lxd#9424]
# Required information

 * Distribution: Alma Linux
 * Distribution version: 8.4 (Electric Cheetah
 * The output of "lxc info" or if that fails:
    Kernel version:
   ```YAML
    kernel: Linux
    kernel_architecture: x86_64
    kernel_features:
    netnsid_getifaddrs: "true"
    seccomp_listener: "false"
    seccomp_listener_continue: "false"
    shiftfs: "false"
    uevent_injection: "true"
    unpriv_fscaps: "true"
    kernel_version: 4.18.0-305.19.1.el8_4.x86_64
    ```
   * LXC version: 4.19
   * LXD version: 4.19
   * Storage backend in use: lvm

# Issue description
I can't enable the br_netfilter module in a container. The Docker engine requires this one to work with swarm mode. In docker log I get the error:
"starting container failed: error creating external connectivity network: cannot restrict inter-container communication: please ensure that br_netfilter kernel module is loaded". 
If I run `modprobe br_netfilter`:
```bash
modprobe: FATAL: Module br_netfilter not found in directory /lib/modules/4.18.0-305.19.1.el8_4.x86_64
```
If I run `lsmod | grep br_`:
```bash
br_netfilter           24576  0
bridge                192512  1 br_netfilter
```
I have tried:
* Include br_netfilter to profile
* Include br_netfilter to container
* Initialise br_netfilter in the host machine
* Set `security.nesting` as `true`
* Set `security.privileged` as `true`
* Recreate container after changes
* Recreate docker service after changes
* Reboot after changes
* Disable swap

Doesn't work.

# Steps to reproduce

 1. Launch any container.
 2. Run `modprobe br_netfilter`

# Information to attach
Container config:
```YAML
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Almalinux 8 amd64 (20211023_03:30)
  image.os: Almalinux
  image.release: "8"
  image.serial: "20211023_03:30"
  image.type: squashfs
  image.variant: default
  linux.kernel_modules: br_netfilter,bridge,br_netfilter,x_tables,ip_tables,ip_vs,ip_set,ipip,xt_mark,xt_multiport,ip_tunnel,tunnel4,netlink_diag,nf_conntrack,nfnetlink,overlay
  security.nesting: "true"
  volatile.base_image: d7d681ff1d3bcb2a6288dc871f6c9148f22b2cd81477d9ec38a6e860978b1dfe
  volatile.eth0.host_name: veth7ce34e67
  volatile.eth0.hwaddr: 00:16:3e:82:eb:3b
  volatile.idmap.base: "0"
  volatile.idmap.current: '[]'
  volatile.idmap.next: '[]'
  volatile.last_state.idmap: '[]'
  volatile.last_state.power: RUNNING
  volatile.uuid: 5d78359b-c4a4-4f69-a4af-1ed89beffdbe
devices:
  nfs_source:
    path: /backup/nfs
    source: /backup/nfs
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
Profile config:
```YAML
config:
  linux.kernel_modules: overlay,nf_nat,ip_tables,ip6_tables,netlink_diag,br_netfilter,xt_conntrack,nf_conntrack,ip_vs,vxlan
  security.nesting: "true"
  security.privileged: "true"
description: Default LXD profile
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: virbr10
    type: nic
  root:
    path: /
    pool: default
    type: disk
name: default
used_by:
- /1.0/instances/prod-master
- /1.0/instances/prod-node-0
```
